import { test, expect, type Page } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

// ─── Test configuration ─────────────────────────────────────────
const BASE_URL = 'http://localhost:5000';
const SCREENSHOT_DIR = path.join(__dirname, 'screenshots');
const RESULTS_DIR = path.join(__dirname, 'results');

// Business queries — use specific business names likely to return autocomplete results.
// Adjust these if they don't resolve in your market.
const TEST_BUSINESSES = [
  {
    id: 'strong-local',
    query: 'DrainWorks Plumbing Toronto',
    description: 'Strong local business — expected strong LP presence',
  },
  {
    id: 'moderate-business',
    query: 'Mr. Locksmith Toronto',
    description: 'Moderate business — locksmith trade',
  },
  {
    id: 'niche-business',
    query: 'Toronto Key Fob Copy',
    description: 'Niche/misaligned — fob services detected as locksmith',
  },
];

// ─── Helpers ─────────────────────────────────────────────────────

function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

/** Wait for the report to be fully generated by watching for score breakdown text. */
async function waitForReport(page: Page, timeoutMs = 150_000) {
  // First wait for the busy/loading state to appear (or skip if instant cache)
  const busyOrReport = await Promise.race([
    page.waitForSelector('text=Running your audit', { timeout: 15_000 }).then(() => 'busy'),
    page.waitForSelector('text=Your Score Breakdown', { timeout: 15_000 }).then(() => 'report'),
  ]).catch(() => 'neither');

  if (busyOrReport === 'report') return; // cached report, already loaded

  // Wait for report to finish generating
  await page.waitForSelector('text=Your Score Breakdown', { timeout: timeoutMs });

  // Give the score animation a moment to settle
  await page.waitForTimeout(1500);
}

/** Extract audit data from the rendered report via DOM inspection. */
async function extractReportData(page: Page) {
  return page.evaluate(() => {
    const data: Record<string, any> = {};

    // Score circle — find the SVG text with the score number
    const scoreSvgTexts = document.querySelectorAll('svg text');
    for (const t of scoreSvgTexts) {
      const val = parseInt(t.textContent || '', 10);
      if (!isNaN(val) && val >= 0 && val <= 100 && t.getAttribute('font-weight') === '700') {
        data.totalScore = val;
        break;
      }
    }

    // Grade pill — find element containing "Grade X"
    const allElements = document.querySelectorAll('div');
    for (const el of allElements) {
      const txt = el.textContent?.trim();
      if (txt && /^Grade [A-D]$/.test(txt)) {
        data.grade = txt.replace('Grade ', '');
        break;
      }
    }

    // Score breakdown rows — extract label + score from "Your Score Breakdown" section
    const breakdownRows: Array<{ label: string; score: string }> = [];
    const allSpans = document.querySelectorAll('span');
    let inBreakdown = false;
    for (const span of allSpans) {
      const txt = span.textContent?.trim() || '';
      if (txt === 'Your Score Breakdown') { inBreakdown = true; continue; }
      if (!inBreakdown) continue;
      // Score values like "15/25", "8/20"
      if (/^\d+\/\d+$/.test(txt)) {
        breakdownRows.push({ label: '', score: txt });
      }
    }
    data.breakdownRowCount = breakdownRows.length;
    data.breakdownScores = breakdownRows.map(r => r.score);

    // Keyword table — extract rows from the Website tab if visible
    // (We'll switch tabs and re-extract in the test)

    // Tab labels
    const buttons = document.querySelectorAll('button');
    const tabLabels: string[] = [];
    for (const btn of buttons) {
      const txt = btn.textContent?.trim();
      if (txt === 'Google Maps' || txt === 'Website' || txt === 'Action Plan') {
        tabLabels.push(txt);
      }
    }
    data.tabs = tabLabels;

    return data;
  });
}

/** Extract keyword table data from the Website tab. */
async function extractKeywordData(page: Page) {
  return page.evaluate(() => {
    const keywords: Array<{
      keyword: string;
      volume: string;
      cpc: string;
      rank: string;
      visibility: string;
    }> = [];

    // Find keyword section — look for rows with keyword data pattern
    // Each row is a flex div with: keyword, vol, cpc, rank, visibility pill
    const rows = document.querySelectorAll('.audit-page div, div');
    // Simpler approach: find elements that look like keyword rows
    // by looking for rank patterns (#N, LP #N, —) near CPC patterns ($N, —)
    const allText = document.body.innerText;
    // Instead, find the keyword section and scrape structured data
    const flexRows = document.querySelectorAll('div[style]');
    for (const row of flexRows) {
      const style = row.getAttribute('style') || '';
      // Keyword rows have display:flex, alignItems:center, and borderBottom
      if (!style.includes('display: flex') || !style.includes('border-bottom')) continue;
      const spans = row.querySelectorAll('span');
      if (spans.length < 4) continue;
      const texts = Array.from(spans).map(s => s.textContent?.trim() || '');
      // Heuristic: a keyword row has a keyword (longer text), then short numeric/dash values
      const keyword = texts[0];
      if (!keyword || keyword.length < 3) continue;
      if (/^(Keyword|Vol\.|CPC|Rank|Visibility)$/i.test(keyword)) continue; // header row
      // Check if this looks like a data row
      const hasRankOrDash = texts.some(t => /^(#\d+|LP\s*#?\d+|—)$/.test(t));
      if (!hasRankOrDash) continue;
      keywords.push({
        keyword,
        volume: texts[1] || '—',
        cpc: texts[2] || '—',
        rank: texts[3] || '—',
        visibility: texts[4] || '—',
      });
    }

    return keywords;
  });
}

// ─── Tests ───────────────────────────────────────────────────────

test.describe('Audit Flow E2E', () => {
  test.beforeAll(() => {
    ensureDir(SCREENSHOT_DIR);
    ensureDir(RESULTS_DIR);
  });

  for (const biz of TEST_BUSINESSES) {
    test(`Full audit flow — ${biz.id}: ${biz.description}`, async ({ page }) => {
      test.setTimeout(180_000); // 3 min — report generation can be slow

      const results: Record<string, any> = {
        testId: biz.id,
        query: biz.query,
        timestamp: new Date().toISOString(),
        assertions: {},
        diagnostics: {},
      };

      // ─── 1. Navigate to audit page ───
      await page.goto(`${BASE_URL}/free-audit`, { waitUntil: 'networkidle', timeout: 20_000 });
      const title = page.getByTestId('text-audit-title');
      await expect(title).toBeVisible({ timeout: 10_000 });
      results.assertions.pageLoaded = true;

      // ─── 2. Type business query ───
      const searchInput = page.getByTestId('input-audit-search');
      await expect(searchInput).toBeVisible();
      await searchInput.fill(biz.query);

      // ─── 3. Wait for suggestions dropdown ───
      const suggestionsList = page.getByTestId('list-suggestions');
      await expect(suggestionsList).toBeVisible({ timeout: 15_000 });

      // Check we got at least one suggestion
      const suggestions = suggestionsList.locator('button');
      const count = await suggestions.count();
      results.diagnostics.suggestionCount = count;

      if (count === 0) {
        // No results — take screenshot and skip (API may not return results for this query)
        await page.screenshot({ path: path.join(SCREENSHOT_DIR, `${biz.id}-no-suggestions.png`), fullPage: true });
        results.assertions.suggestionsFound = false;
        fs.writeFileSync(
          path.join(RESULTS_DIR, `${biz.id}.json`),
          JSON.stringify(results, null, 2)
        );
        test.skip(true, `No suggestions returned for "${biz.query}" — likely API or query issue`);
        return;
      }
      results.assertions.suggestionsFound = true;

      // ─── 4. Click first suggestion ───
      await suggestions.first().click();

      // ─── 5. Wait for report generation ───
      await waitForReport(page, 150_000);
      results.assertions.reportGenerated = true;

      // Screenshot: full report
      await page.screenshot({ path: path.join(SCREENSHOT_DIR, `${biz.id}-report.png`), fullPage: true });

      // ─── 6. Extract report data ───
      const reportData = await extractReportData(page);
      results.diagnostics.reportData = reportData;

      // ─── VALIDATION A: Score integrity ───

      // A1. Total score exists and is 0-100
      // STRICT: score must be a number in range
      expect(reportData.totalScore, 'Total score should be a number 0-100').toBeGreaterThanOrEqual(0);
      expect(reportData.totalScore).toBeLessThanOrEqual(100);
      results.assertions.scoreInRange = true;

      // A2. Grade exists and is valid
      // STRICT: grade must be A, B, C, or D
      expect(['A', 'B', 'C', 'D'], 'Grade should be A/B/C/D').toContain(reportData.grade);
      results.assertions.gradeValid = true;

      // A3. Score breakdown has 6 metric rows
      // DIAGNOSTIC: may vary if some metrics are null
      results.diagnostics.breakdownRowCount = reportData.breakdownRowCount;
      if (reportData.breakdownRowCount < 5) {
        console.warn(`[${biz.id}] Only ${reportData.breakdownRowCount} breakdown rows found (expected 6)`);
      }

      // A4. Score is not suspiciously zero when we expect visibility
      // DIAGNOSTIC: log warning but don't fail — depends on actual business
      if (reportData.totalScore === 0) {
        console.warn(`[${biz.id}] Total score is 0 — may indicate scoring issue`);
      }
      results.diagnostics.totalScore = reportData.totalScore;
      results.diagnostics.grade = reportData.grade;

      // ─── VALIDATION B: Tabs exist and work ───

      // B1. All 3 tabs present
      // STRICT
      expect(reportData.tabs).toContain('Google Maps');
      expect(reportData.tabs).toContain('Website');
      expect(reportData.tabs).toContain('Action Plan');
      results.assertions.allTabsPresent = true;

      // B2. Switch to Website tab
      const websiteTab = page.locator('button', { hasText: 'Website' });
      await websiteTab.click();
      await page.waitForTimeout(500);

      // Screenshot: website tab
      await page.screenshot({ path: path.join(SCREENSHOT_DIR, `${biz.id}-website-tab.png`), fullPage: true });

      // B3. Switch to Action Plan tab
      const planTab = page.locator('button', { hasText: 'Action Plan' });
      await planTab.click();
      await page.waitForTimeout(500);

      // Screenshot: action plan tab
      await page.screenshot({ path: path.join(SCREENSHOT_DIR, `${biz.id}-plan-tab.png`), fullPage: true });

      // Switch back to Google Maps tab for remaining checks
      const mapsTab = page.locator('button', { hasText: 'Google Maps' });
      await mapsTab.click();
      await page.waitForTimeout(500);
      results.assertions.tabSwitchingWorks = true;

      // ─── VALIDATION C: No stuck loading states ───

      // STRICT: no loading spinners should remain after report is ready
      const spinners = page.locator('text=Measuring website speed');
      // This is expected if speed test is still running — just diagnostic
      const spinnerVisible = await spinners.isVisible().catch(() => false);
      results.diagnostics.speedStillLoading = spinnerVisible;

      // ─── VALIDATION D: Keyword data on Website tab ───

      // Switch to Website tab to check keywords
      await websiteTab.click();
      await page.waitForTimeout(800);

      const keywordData = await extractKeywordData(page);
      results.diagnostics.keywordRows = keywordData;
      results.diagnostics.keywordCount = keywordData.length;

      if (keywordData.length > 0) {
        // D1. CPC values should be "$X", "$X.Y", or "—" — never "$0.00"
        // STRICT
        for (const kw of keywordData) {
          if (kw.cpc && kw.cpc !== '—') {
            expect(kw.cpc, `CPC for "${kw.keyword}" should not be $0.00`).not.toBe('$0.00');
            expect(kw.cpc, `CPC for "${kw.keyword}" should start with $`).toMatch(/^\$/);
          }
        }
        results.assertions.cpcFormatValid = true;

        // D2. Volume should be a number or "—" — never literally "0" unless truly zero
        // DIAGNOSTIC: just log
        const zeroVolumes = keywordData.filter(k => k.volume === '0');
        if (zeroVolumes.length > 0) {
          console.warn(`[${biz.id}] ${zeroVolumes.length} keywords show volume=0 — may be data issue`);
        }
        results.diagnostics.zeroVolumeCount = zeroVolumes.length;

        // D3. No row should show rank="Not ranking" — old bug, should show "—" or LP#N
        // STRICT
        for (const kw of keywordData) {
          expect(kw.rank, `Rank for "${kw.keyword}" should not say "Not ranking"`).not.toBe('Not ranking');
        }
        results.assertions.noLegacyNotRanking = true;

        // D4. LP labels should use "LP #N" format
        // DIAGNOSTIC
        const lpRows = keywordData.filter(k => k.rank.startsWith('LP'));
        results.diagnostics.localPackKeywords = lpRows.length;
        for (const kw of lpRows) {
          expect(kw.rank, `LP rank for "${kw.keyword}" should match LP #N format`).toMatch(/^LP\s*#\d+$/);
        }

        // D5. Check for rank/visibility contradiction
        // STRICT: if rank shows "—" (no rank at all), visibility should not say "strong" or "dominant"
        for (const kw of keywordData) {
          if (kw.rank === '—') {
            const vis = kw.visibility?.toLowerCase() || '';
            expect(
              vis,
              `"${kw.keyword}" shows no rank but visibility="${kw.visibility}" — contradiction`
            ).not.toMatch(/^(strong|dominant)$/);
          }
        }
        results.assertions.noRankVisibilityContradiction = true;
      } else {
        console.warn(`[${biz.id}] No keyword rows found on Website tab — section may not have rendered`);
        results.diagnostics.keywordSectionMissing = true;
      }

      // ─── VALIDATION E: Score floor for local pack presence ───

      // If we found LP keywords, the visibility score should have a floor
      // DIAGNOSTIC: requires reading the actual score from breakdown
      if (keywordData.some(k => k.rank.startsWith('LP'))) {
        const visScoreStr = reportData.breakdownScores?.find((s: string) => {
          const [num, max] = s.split('/').map(Number);
          return max === 20; // Search Visibility is X/20
        });
        if (visScoreStr) {
          const visScore = parseInt(visScoreStr.split('/')[0], 10);
          results.diagnostics.visibilityScore = visScore;
          // STRICT: LP presence should give at least 6/20
          expect(visScore, 'Visibility score with LP presence should be >= 6').toBeGreaterThanOrEqual(6);
          results.assertions.localPackFloorApplied = true;
        }
      }

      // ─── Save results ───
      fs.writeFileSync(
        path.join(RESULTS_DIR, `${biz.id}.json`),
        JSON.stringify(results, null, 2)
      );

      console.log(`\n[${biz.id}] Test complete:`);
      console.log(`  Score: ${reportData.totalScore}/100 (Grade ${reportData.grade})`);
      console.log(`  Breakdown rows: ${reportData.breakdownRowCount}`);
      console.log(`  Keywords found: ${keywordData.length}`);
      console.log(`  LP keywords: ${keywordData.filter(k => k.rank.startsWith('LP')).length}`);
      console.log(`  Results saved to: tests/e2e/results/${biz.id}.json`);
    });
  }
});
