-- Wave AQ-3 — public API v1 webhook DELIVERY queue.
--
-- AJ-6 (migration 0021) shipped the webhook MANAGEMENT surface (create /
-- list / delete via /api/v1/webhooks). This migration ships the actual
-- event-DELIVERY surface: a durable in-DB queue of pending POSTs that the
-- background worker drains every 30s.
--
-- Lifecycle:
--   pending  → succeeded   (HTTP 2xx from subscriber)
--   pending  → failed      (HTTP non-2xx or transport error; retried with
--                          exponential backoff at 1m, 5m, 30m, 2h, 12h)
--   failed   → pending     (worker re-arms the same row by advancing
--                          next_attempt_at and bumping attempt_count)
--   failed   → dead        (after 5 attempts; no further retries)
--
-- Idempotency:
--   - event_id is generated by the dispatcher (cuid) and is what we
--     surface in the webhook payload's `id` field. Subscribers can use it
--     to dedup re-deliveries on their side.
--   - The worker claims rows by transitioning status atomically; a server
--     restart during a tick won't double-fire because the row is set to
--     'succeeded' (or back to 'pending' with bumped attempt) by the time
--     the HTTP POST returns.
--
-- Admin replay: the admin endpoint resets a 'failed' or 'dead' row back
-- to 'pending' with next_attempt_at = now() so the next worker tick picks
-- it up. attempt_count is reset to 0 so the row gets the full retry
-- ladder again.

CREATE TABLE IF NOT EXISTS "api_webhook_deliveries" (
  "id"                   bigserial PRIMARY KEY,
  "webhook_id"           text NOT NULL,
  "event_id"             text NOT NULL,
  "event_type"           text NOT NULL,
  "payload"              jsonb NOT NULL,
  "status"               text NOT NULL DEFAULT 'pending',
  "attempt_count"        integer NOT NULL DEFAULT 0,
  "next_attempt_at"      timestamp NOT NULL DEFAULT now(),
  "last_response_status" integer,
  "last_response_body"   text,
  "last_error"           text,
  "succeeded_at"         timestamp,
  "created_at"           timestamp NOT NULL DEFAULT now()
);

DO $$ BEGIN
  ALTER TABLE "api_webhook_deliveries"
    ADD CONSTRAINT "api_webhook_deliveries_webhook_id_fk"
    FOREIGN KEY ("webhook_id") REFERENCES "public"."api_webhooks"("id")
    ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Worker hot path: claim pending rows due now, oldest first.
CREATE INDEX IF NOT EXISTS "idx_api_webhook_deliveries_pending_due"
  ON "api_webhook_deliveries" ("next_attempt_at")
  WHERE status = 'pending';

-- Admin observability: last-20 per webhook, newest first.
CREATE INDEX IF NOT EXISTS "idx_api_webhook_deliveries_webhook_created"
  ON "api_webhook_deliveries" ("webhook_id", "created_at" DESC);
