-- Wave BF-6 — MapGuard Snapshot persistence.
--
-- Stores publicly shareable GBP rank-grid + audit snapshots generated by the
-- free /tools/map-snapshot tool. Snapshots are addressed by a public slug so
-- a user can share their result without exposing the numeric id. Heatmap +
-- audit payloads are stored as JSON because they're consumed verbatim by the
-- shared view and not queried structurally.
--
-- Retention: no automatic sweep this wave — snapshots are small (<2KB JSON)
-- and act as social proof links. Pruning lands with the next privacy review
-- if volume justifies it.

CREATE TABLE IF NOT EXISTS map_snapshots (
  id SERIAL PRIMARY KEY,
  -- Public-facing slug (short base36 hash). Used in the shareable URL
  -- /snapshot/<slug> so the numeric id never leaks externally.
  slug VARCHAR(32) NOT NULL UNIQUE,
  business_name VARCHAR(200) NOT NULL,
  -- Resolved business address (best-effort from Places, blank for mock).
  business_address VARCHAR(400),
  location_lat DOUBLE PRECISION NOT NULL,
  location_lng DOUBLE PRECISION NOT NULL,
  -- Keywords the user requested ranking for, JSON array of strings.
  keywords_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  -- 5x5 grid of { lat, lng, keyword, rank, distanceKm } cells.
  heatmap_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  -- 10-card scorecard: array of { id, label, status, score, details, ctaCardName? }.
  audit_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  -- "real" when a live Google API call backed the snapshot, "mock"
  -- when fallback data was synthesised. Useful for support triage and
  -- for filtering social-proof analytics.
  source VARCHAR(16) NOT NULL DEFAULT 'mock',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_map_snapshots_slug ON map_snapshots(slug);
CREATE INDEX IF NOT EXISTS idx_map_snapshots_created ON map_snapshots(created_at DESC);
