-- 0063_content_pipeline.sql
--
-- Wave 20 — ContentFlow as the single content factory.
--
-- ContentFlow is the only generator. RankFlow + SocialSync become delivery
-- channels that call `requestContent()` and receive results. Both new tables
-- are additive: existing content_drafts / content_approvals / content_assets
-- are untouched.
--
-- content_requests       — top-level request tracking (one row per call).
-- content_pipeline_log   — append-only state-transition log per request.
--
-- Safe to re-run (IF NOT EXISTS everywhere).

CREATE TABLE IF NOT EXISTS content_requests (
  id SERIAL PRIMARY KEY,
  request_id VARCHAR(64) NOT NULL UNIQUE,        -- uuid generated by caller
  source VARCHAR(20) NOT NULL,                   -- 'rankflow' | 'socialsync' | 'contentflow' | 'manual'
  type VARCHAR(20) NOT NULL,                     -- 'article' | 'social_post' | 'image' | 'video'
  client_id INTEGER,                             -- references clients.id; nullable for system-level requests
  topic TEXT NOT NULL,
  request_payload JSONB NOT NULL,
  current_stage VARCHAR(30) NOT NULL DEFAULT 'requested',
  -- 'requested' | 'generating' | 'quality_check' | 'approved' | 'failed'
  result_payload JSONB,
  quality_score INTEGER,
  error_count INTEGER NOT NULL DEFAULT 0,
  draft_id INTEGER,                              -- back-link to content_drafts.id when applicable
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_content_requests_client_id
  ON content_requests (client_id);
CREATE INDEX IF NOT EXISTS idx_content_requests_source
  ON content_requests (source);
CREATE INDEX IF NOT EXISTS idx_content_requests_current_stage
  ON content_requests (current_stage);
CREATE INDEX IF NOT EXISTS idx_content_requests_created_at
  ON content_requests (created_at DESC);

CREATE TABLE IF NOT EXISTS content_pipeline_log (
  id SERIAL PRIMARY KEY,
  request_id VARCHAR(64) NOT NULL,               -- matches content_requests.request_id
  source VARCHAR(20) NOT NULL,                   -- duplicated for fast filtering
  stage VARCHAR(30) NOT NULL,
  -- 'requested' | 'generating' | 'quality_check' | 'approved' | 'failed' | 'retry'
  payload JSONB,
  errors JSONB,                                  -- array of ContentError objects
  recorded_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_content_pipeline_log_request_id
  ON content_pipeline_log (request_id);
CREATE INDEX IF NOT EXISTS idx_content_pipeline_log_source
  ON content_pipeline_log (source);
CREATE INDEX IF NOT EXISTS idx_content_pipeline_log_stage
  ON content_pipeline_log (stage);
CREATE INDEX IF NOT EXISTS idx_content_pipeline_log_recorded_at
  ON content_pipeline_log (recorded_at DESC);
