import type { Express } from "express";
import { type Server } from "http";
import auditRouter from "../auditRoutes";

import { registerAuthRoutes } from "./authRoutes";
import { registerMarketingRoutes } from "./marketingRoutes";
import { registerMarketingWaitlistRoutes } from "./marketingWaitlistRoutes";
import { registerAiRoutes } from "./aiRoutes";
import { registerCalculatorRoutes } from "./calculatorRoutes";
import { registerLeadRoutes } from "./leadRoutes";
import { registerDashboardRoutes } from "./dashboardRoutes";
import { registerDomainRoutes } from "./domainRoutes";
import { registerBookingRoutes } from "./bookingRoutes";
import { registerStripeRoutes } from "./stripeRoutes";
import { registerTwilioRoutes } from "./twilioRoutes";
import { registerChatRoutes } from "./chatRoutes";
import { registerAdminRoutes } from "./adminRoutes";
import { registerAdminCrmRoutes } from "./adminCrmRoutes";
import { registerAdminClientCostsRoutes } from "./adminClientCostsRoutes";
import { registerAdminToolRoutes } from "./adminToolRoutes";
import { registerAiChannelSettingsRoutes } from "./aiChannelSettingsRoutes";
import { registerAdminAiChannelGatesRoutes } from "./adminAiChannelGatesRoutes";
import { registerInboundEmailRoutes } from "./inboundEmailRoutes";
import { registerFounderNotifyRoutes } from "./founderNotifyRoutes";
import { registerStripeBillingRoutes } from "./stripeBillingRoutes";
import { registerWidgetDepositRoutes } from "./widgetDepositRoutes";
import { registerBillingPortalRoute } from "./billingPortalRoute";
import { registerEmailTrackingRoutes } from "./emailTrackingRoutes";
import { registerSendgridWebhookRoutes } from "./sendgridWebhookRoutes";
import { registerOnboardingPublicRoutes } from "./onboardingPublicRoutes";
import { registerVapiRoutes } from "./vapiRoutes";
import { registerPublicCheckoutRoutes } from "./publicCheckoutRoutes";
import { registerIntegrationHealthRoutes } from "./integrationHealthRoutes";
import { registerPortalRoutes } from "./portalRoutes";
import { registerPortalEmailDomainRoutes } from "./portalEmailDomainRoutes";
import { registerPortalSecurityRoutes } from "./portalSecurityRoutes";
import { registerAdminSupportRoutes } from "./adminSupportRoutes";
import { registerMissedCallLeadRoutes } from "./missedCallLeadRoutes";
import { registerDemoLeadRoutes } from "./demoLeadRoutes";
import { registerAdminOpsRoutes, registerBrandAvailabilityRoutes } from "./adminOpsRoutes";
import { registerAdminOutboundRoutes } from "./adminOutboundRoutes";
import { registerAdminOutreachSequencesRoutes } from "./adminOutreachSequencesRoutes";
import { registerReviewPublicRoutes } from "./reviewPublicRoutes";
import { registerWidgetRoutes } from "./widgetRoutes";
import { registerWidgetFreetoolsRoutes } from "./widgetFreetoolsRoutes";
import { registerPortalFreetoolsRoutes } from "./portalFreetoolsRoutes";
import { registerReviewFunnelRoutes } from "./reviewFunnelRoutes";
import { registerPortalReviewLinkRoutes } from "./portalReviewLinkRoutes";
import { registerServiceAreaMapRoutes } from "./serviceAreaMapRoutes";
import { registerMapguardRoutes } from "./mapguardRoutes";
import { registerSocialSyncRoutes } from "./socialSyncRoutes";
import { registerReputationRoutes } from "./reputationRoutes";
import { registerSalesRoutes } from "./salesRoutes";
import { registerMediaRoute } from "../services/socialSync/mediaService";
import { registerRankFlowRoutes } from "./rankflowRoutes";
import { registerContentFlowRoutes } from "./contentflowRoutes";
import { registerUnsubscribeRoutes } from "./unsubscribeRoutes";
import { registerEmailChartsRoute } from "../services/emailCharts";
import { registerAdminSupplierRoutes } from "./adminSupplierRoutes";
import { registerSupplierWebhookRoutes } from "./supplierWebhookRoutes";
import { registerAdminServiceRoutes } from "./adminServiceRoutes";
import { registerApprovalRoutes } from "./approvalRoutes";
import { registerDemoRoutes } from "./demoRoutes";
import { registerBookingApiRoutes } from "./bookingApiRoutes";
import { registerBookflowRoutes } from "./bookflowRoutes";
import { registerAdminAlertRoutes } from "./adminAlertRoutes";
import { registerChatAttachmentRoutes } from "./chatAttachmentRoutes";
import { registerTradelineSetupRoutes } from "./tradelineSetupRoutes";
import { registerTradelineWidgetRoutes } from "./tradelineWidgetRoutes";
import { registerAdminTradelineSetupsRoutes } from "./adminTradelineSetupsRoutes";
import { registerAdminTradelineTemplatesRoutes } from "./adminTradelineTemplatesRoutes";
import { registerTradelineChatInstallRoutes } from "./tradelineChatInstallRoutes";
import { registerAdminTradelineLearningRoutes } from "./adminTradelineLearningRoutes";
import { registerMobileAuthRoutes } from "./mobileAuthRoutes";
import { registerMobileApiRoutes } from "./mobileApiRoutes";
import { registerMobileVoiceRoutes } from "./mobileVoiceRoutes";
import { registerMobileAiRoutes } from "./mobileAiRoutes";
import { registerMobileAiImagesRoutes } from "./mobileAiImagesRoutes";
import { registerMobileAiVoiceRoutes } from "./mobileAiVoiceRoutes";
import { registerMobileContactRoutes } from "./mobileContactRoutes";
import { registerTwilioVoiceCallbackRoutes } from "./twilioVoiceCallbackRoutes";
import { registerVoicemailRoutes } from "./voicemailRoutes";
import { registerQuoteQuickAiChatRoutes } from "./quotequickAiChatRoutes";
import { registerAiImageToTemplateRoutes } from "./aiImageToTemplateRoutes";
import { registerAiDemoRoutes } from "./aiDemoRoutes";
import { registerAdminAiBudgetRoutes } from "./adminAiBudgetRoutes";
import { registerTwilioCommsRoutes } from "./twilioCommsRoutes";
import { registerAdminContactsRoutes } from "./adminContactsRoutes";
import { registerWidgetSchedulingRoutes } from "./widgetSchedulingRoutes";
import { registerQuoteSnapshotRoutes } from "./quoteSnapshotRoutes";
import { registerAdminQuoteQuickTemplatesRoutes } from "./adminQuoteQuickTemplatesRoutes";
import { registerAdminQuoteQuickTradesRoutes } from "./adminQuoteQuickTradesRoutes";
import { registerQuoteQuickPublicRoutes } from "./quotequickPublicRoutes";
import { registerAdminApiPlatformRoutes } from "./adminApiPlatformRoutes";
import { registerPortalApiKeysRoutes } from "./portalApiKeysRoutes";
import { registerPortalBrandKitsRoutes } from "./portalBrandKitsRoutes";
import { registerAdminTradelineVoicesRoutes } from "./adminTradelineVoicesRoutes";
import { registerPortalTradelineKnowledgeRoutes } from "./portalTradelineKnowledgeRoutes";
import { registerAdminAuditLogRoutes } from "./adminAuditLogRoutes";
import { registerAdminFileRetentionRoutes } from "./adminFileRetentionRoutes";
import { registerAdminImpersonateRoutes } from "./adminImpersonateRoutes";
import { registerAdminMobilePreviewRoutes } from "./adminMobilePreviewRoutes";
import { registerAdminAiActivityRoutes } from "./adminAiActivityRoutes";
import { registerCalculatorAnalyticsRoutes } from "./calculatorAnalyticsRoutes";
import { registerMapSnapshotRoutes } from "./mapSnapshotRoutes";
import { registerApiV1Routes } from "./apiV1";

export async function registerRoutes(
  httpServer: Server,
  app: Express
): Promise<Server> {
  app.use("/api/audit", auditRouter);

  registerAuthRoutes(app);
  registerMarketingRoutes(app);
  registerMarketingWaitlistRoutes(app);
  registerUnsubscribeRoutes(app);
  registerAiRoutes(app);
  registerCalculatorRoutes(app);
  registerLeadRoutes(app);
  registerDashboardRoutes(app);
  registerDomainRoutes(app);
  registerBookingRoutes(app);
  registerStripeRoutes(app);
  registerTwilioRoutes(app);
  registerChatRoutes(app);
  registerAdminRoutes(app);
  registerAdminCrmRoutes(app);
  registerAdminClientCostsRoutes(app);
  registerAdminToolRoutes(app);
  registerAiChannelSettingsRoutes(app);
  registerAdminAiChannelGatesRoutes(app);
  registerStripeBillingRoutes(app);
  registerWidgetDepositRoutes(app);
  registerBillingPortalRoute(app);
  registerEmailTrackingRoutes(app);
  registerSendgridWebhookRoutes(app);
  registerInboundEmailRoutes(app);
  registerFounderNotifyRoutes(app);
  registerOnboardingPublicRoutes(app);
  registerVapiRoutes(app);
  registerPublicCheckoutRoutes(app);
  registerIntegrationHealthRoutes(app);
  registerPortalRoutes(app);
  registerPortalEmailDomainRoutes(app);
  registerPortalSecurityRoutes(app);
  registerAdminSupportRoutes(app);
  registerMissedCallLeadRoutes(app);
  registerDemoLeadRoutes(app);
  registerAdminOpsRoutes(app);
  registerBrandAvailabilityRoutes(app);
  registerAdminOutboundRoutes(app);
  registerAdminOutreachSequencesRoutes(app);
  registerMapguardRoutes(app);
  registerSocialSyncRoutes(app);
  registerReputationRoutes(app);
  registerSalesRoutes(app);
  registerMediaRoute(app);
  registerReviewPublicRoutes(app);
  registerWidgetRoutes(app);
  registerWidgetFreetoolsRoutes(app);
  registerPortalFreetoolsRoutes(app);
  registerReviewFunnelRoutes(app);
  registerPortalReviewLinkRoutes(app);
  registerServiceAreaMapRoutes(app);
  registerRankFlowRoutes(app);
  registerContentFlowRoutes(app);
  registerEmailChartsRoute(app);
  registerAdminSupplierRoutes(app);
  registerSupplierWebhookRoutes(app);
  registerAdminServiceRoutes(app);
  registerApprovalRoutes(app);
  registerDemoRoutes(app);
  registerBookingApiRoutes(app);
  registerBookflowRoutes(app);
  registerAdminAlertRoutes(app);
  registerChatAttachmentRoutes(app);
  registerTradelineSetupRoutes(app);
  registerTradelineWidgetRoutes(app);
  registerAdminTradelineSetupsRoutes(app);
  registerAdminTradelineTemplatesRoutes(app);
  registerTradelineChatInstallRoutes(app);
  registerAdminTradelineLearningRoutes(app);
  registerMobileAuthRoutes(app);
  registerMobileApiRoutes(app);
  registerMobileVoiceRoutes(app);
  registerMobileAiRoutes(app);
  registerMobileAiImagesRoutes(app);
  registerMobileAiVoiceRoutes(app);
  registerMobileContactRoutes(app);
  registerTwilioVoiceCallbackRoutes(app);
  registerVoicemailRoutes(app);
  registerQuoteQuickAiChatRoutes(app);
  registerAiImageToTemplateRoutes(app);
  registerAiDemoRoutes(app);
  registerAdminAiBudgetRoutes(app);
  registerTwilioCommsRoutes(app);
  registerAdminContactsRoutes(app);
  registerWidgetSchedulingRoutes(app);
  registerQuoteSnapshotRoutes(app);
  registerAdminQuoteQuickTemplatesRoutes(app);
  registerAdminQuoteQuickTradesRoutes(app);
  registerQuoteQuickPublicRoutes(app);
  registerAdminApiPlatformRoutes(app);
  registerPortalApiKeysRoutes(app);
  registerPortalBrandKitsRoutes(app);
  registerAdminTradelineVoicesRoutes(app);
  registerPortalTradelineKnowledgeRoutes(app);
  registerAdminAuditLogRoutes(app);
  registerAdminFileRetentionRoutes(app);
  registerAdminImpersonateRoutes(app);
  registerAdminMobilePreviewRoutes(app);
  registerAdminAiActivityRoutes(app);
  registerCalculatorAnalyticsRoutes(app);
  registerMapSnapshotRoutes(app);
  registerApiV1Routes(app);

  return httpServer;
}
