import type { Express } from "express";
import { type Server } from "http";
import auditRouter from "../auditRoutes";

import { registerAuthRoutes } from "./authRoutes";
import { registerMarketingRoutes } from "./marketingRoutes";
import { registerAiRoutes } from "./aiRoutes";
import { registerCalculatorRoutes } from "./calculatorRoutes";
import { registerLeadRoutes } from "./leadRoutes";
import { registerDashboardRoutes } from "./dashboardRoutes";
import { registerDomainRoutes } from "./domainRoutes";
import { registerBookingRoutes } from "./bookingRoutes";
import { registerStripeRoutes } from "./stripeRoutes";
import { registerTwilioRoutes } from "./twilioRoutes";
import { registerChatRoutes } from "./chatRoutes";
import { registerAdminRoutes } from "./adminRoutes";
import { registerAdminCrmRoutes } from "./adminCrmRoutes";
import { registerAdminToolRoutes } from "./adminToolRoutes";
import { registerStripeBillingRoutes } from "./stripeBillingRoutes";
import { registerBillingPortalRoute } from "./billingPortalRoute";
import { registerEmailTrackingRoutes } from "./emailTrackingRoutes";
import { registerSendgridWebhookRoutes } from "./sendgridWebhookRoutes";
import { registerOnboardingPublicRoutes } from "./onboardingPublicRoutes";
import { registerVapiRoutes } from "./vapiRoutes";
import { registerPublicCheckoutRoutes } from "./publicCheckoutRoutes";
import { registerIntegrationHealthRoutes } from "./integrationHealthRoutes";
import { registerPortalRoutes } from "./portalRoutes";
import { registerPortalEmailDomainRoutes } from "./portalEmailDomainRoutes";
import { registerAdminSupportRoutes } from "./adminSupportRoutes";
import { registerMissedCallLeadRoutes } from "./missedCallLeadRoutes";
import { registerDemoLeadRoutes } from "./demoLeadRoutes";
import { registerAdminOpsRoutes, registerBrandAvailabilityRoutes } from "./adminOpsRoutes";
import { registerAdminOutboundRoutes } from "./adminOutboundRoutes";
import { registerReviewPublicRoutes } from "./reviewPublicRoutes";
import { registerWidgetRoutes } from "./widgetRoutes";
import { registerMapguardRoutes } from "./mapguardRoutes";
import { registerSocialSyncRoutes } from "./socialSyncRoutes";
import { registerReputationRoutes } from "./reputationRoutes";
import { registerSalesRoutes } from "./salesRoutes";
import { registerMediaRoute } from "../services/socialSync/mediaService";
import { registerRankFlowRoutes } from "./rankflowRoutes";
import { registerContentFlowRoutes } from "./contentflowRoutes";
import { registerUnsubscribeRoutes } from "./unsubscribeRoutes";
import { registerEmailChartsRoute } from "../services/emailCharts";
import { registerAdminSupplierRoutes } from "./adminSupplierRoutes";
import { registerSupplierWebhookRoutes } from "./supplierWebhookRoutes";
import { registerAdminServiceRoutes } from "./adminServiceRoutes";
import { registerApprovalRoutes } from "./approvalRoutes";
import { registerDemoRoutes } from "./demoRoutes";
import { registerBookingApiRoutes } from "./bookingApiRoutes";
import { registerBookflowRoutes } from "./bookflowRoutes";
import { registerAdminAlertRoutes } from "./adminAlertRoutes";
import { registerChatAttachmentRoutes } from "./chatAttachmentRoutes";
import { registerTradelineSetupRoutes } from "./tradelineSetupRoutes";
import { registerTradelineWidgetRoutes } from "./tradelineWidgetRoutes";
import { registerAdminTradelineSetupsRoutes } from "./adminTradelineSetupsRoutes";
import { registerAdminTradelineTemplatesRoutes } from "./adminTradelineTemplatesRoutes";
import { registerTradelineChatInstallRoutes } from "./tradelineChatInstallRoutes";
import { registerAdminTradelineLearningRoutes } from "./adminTradelineLearningRoutes";
import { registerMobileAuthRoutes } from "./mobileAuthRoutes";
import { registerMobileApiRoutes } from "./mobileApiRoutes";
import { registerMobileVoiceRoutes } from "./mobileVoiceRoutes";
import { registerMobileAiRoutes } from "./mobileAiRoutes";
import { registerMobileContactRoutes } from "./mobileContactRoutes";
import { registerTwilioVoiceCallbackRoutes } from "./twilioVoiceCallbackRoutes";
import { registerVoicemailRoutes } from "./voicemailRoutes";

export async function registerRoutes(
  httpServer: Server,
  app: Express
): Promise<Server> {
  app.use("/api/audit", auditRouter);

  registerAuthRoutes(app);
  registerMarketingRoutes(app);
  registerUnsubscribeRoutes(app);
  registerAiRoutes(app);
  registerCalculatorRoutes(app);
  registerLeadRoutes(app);
  registerDashboardRoutes(app);
  registerDomainRoutes(app);
  registerBookingRoutes(app);
  registerStripeRoutes(app);
  registerTwilioRoutes(app);
  registerChatRoutes(app);
  registerAdminRoutes(app);
  registerAdminCrmRoutes(app);
  registerAdminToolRoutes(app);
  registerStripeBillingRoutes(app);
  registerBillingPortalRoute(app);
  registerEmailTrackingRoutes(app);
  registerSendgridWebhookRoutes(app);
  registerOnboardingPublicRoutes(app);
  registerVapiRoutes(app);
  registerPublicCheckoutRoutes(app);
  registerIntegrationHealthRoutes(app);
  registerPortalRoutes(app);
  registerPortalEmailDomainRoutes(app);
  registerAdminSupportRoutes(app);
  registerMissedCallLeadRoutes(app);
  registerDemoLeadRoutes(app);
  registerAdminOpsRoutes(app);
  registerBrandAvailabilityRoutes(app);
  registerAdminOutboundRoutes(app);
  registerMapguardRoutes(app);
  registerSocialSyncRoutes(app);
  registerReputationRoutes(app);
  registerSalesRoutes(app);
  registerMediaRoute(app);
  registerReviewPublicRoutes(app);
  registerWidgetRoutes(app);
  registerRankFlowRoutes(app);
  registerContentFlowRoutes(app);
  registerEmailChartsRoute(app);
  registerAdminSupplierRoutes(app);
  registerSupplierWebhookRoutes(app);
  registerAdminServiceRoutes(app);
  registerApprovalRoutes(app);
  registerDemoRoutes(app);
  registerBookingApiRoutes(app);
  registerBookflowRoutes(app);
  registerAdminAlertRoutes(app);
  registerChatAttachmentRoutes(app);
  registerTradelineSetupRoutes(app);
  registerTradelineWidgetRoutes(app);
  registerAdminTradelineSetupsRoutes(app);
  registerAdminTradelineTemplatesRoutes(app);
  registerTradelineChatInstallRoutes(app);
  registerAdminTradelineLearningRoutes(app);
  registerMobileAuthRoutes(app);
  registerMobileApiRoutes(app);
  registerMobileVoiceRoutes(app);
  registerMobileAiRoutes(app);
  registerMobileContactRoutes(app);
  registerTwilioVoiceCallbackRoutes(app);
  registerVoicemailRoutes(app);

  return httpServer;
}
