/**
 * Wave BF-6 — shareable snapshot view.
 *
 * Reads :slug from the route and loads the persisted snapshot, then renders
 * it in read-only mode via the shared shell. Used as a social-proof asset:
 * users share /snapshot/<slug> with peers / sales prospects.
 */

import { useRoute } from "wouter";
import { useEffect, useState } from "react";
import MarketingLayout from "@/components/marketing/MarketingLayout";
import MapSnapshotShell, {
  type SnapshotResult,
} from "@/components/marketing/map-snapshot/MapSnapshotShell";
import { usePageMeta } from "@/lib/usePageMeta";

export default function MapSnapshotShared() {
  const [, params] = useRoute("/snapshot/:slug");
  const slug = params?.slug || "";
  const [result, setResult] = useState<SnapshotResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  usePageMeta({
    title: result
      ? `${result.businessName} — Google Maps rank snapshot`
      : "Snapshot — MapGuard",
    description:
      result
        ? `Live 5×5 Google Maps rank-grid and GBP audit for ${result.businessName}. Generated by MapGuard Snapshot.`
        : "View a shared Google Maps rank snapshot.",
    canonicalPath: `/snapshot/${slug}`,
  });

  useEffect(() => {
    let cancelled = false;
    async function load() {
      try {
        const r = await fetch(`/api/tools/map-snapshot/${encodeURIComponent(slug)}`);
        if (!r.ok) {
          if (!cancelled) setError("This snapshot link is invalid or expired.");
          return;
        }
        const j = await r.json();
        if (!cancelled) setResult(j as SnapshotResult);
      } catch {
        if (!cancelled) setError("Failed to load snapshot.");
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    if (slug) load();
    return () => {
      cancelled = true;
    };
  }, [slug]);

  return (
    <MarketingLayout>
      <div style={{ padding: "48px 16px 80px", background: "#fafafa", minHeight: "60vh" }}>
        <div style={{ maxWidth: 720, margin: "0 auto 24px", textAlign: "center" }}>
          <h1
            style={{
              fontSize: "clamp(24px, 4vw, 32px)",
              fontWeight: 800,
              color: "#1E1E1E",
              margin: "0 0 8px",
            }}
          >
            Shared Map Snapshot
          </h1>
          <p style={{ color: "#525252", fontSize: 14, margin: 0 }}>
            View-only. Want one for your business?{" "}
            <a href="/tools/map-snapshot" style={{ color: "#0d3cfc", fontWeight: 600 }}>
              Run a free snapshot →
            </a>
          </p>
        </div>

        {loading && (
          <div
            style={{
              textAlign: "center",
              color: "#6b7280",
              fontSize: 14,
              padding: 60,
            }}
          >
            Loading snapshot…
          </div>
        )}
        {error && (
          <div
            role="alert"
            style={{
              maxWidth: 480,
              margin: "0 auto",
              padding: 16,
              background: "#fef2f2",
              border: "1px solid #fecaca",
              color: "#991b1b",
              borderRadius: 10,
              textAlign: "center",
              fontSize: 14,
            }}
          >
            {error}
          </div>
        )}
        {result && <MapSnapshotShell initialResult={result} readOnly />}
      </div>
    </MarketingLayout>
  );
}
