import { Link } from "wouter";
import {
  FileCode2,
  HelpCircle,
  Clock,
  ShieldCheck,
  MapPin,
  PhoneCall,
  Star,
} from "lucide-react";
import PortalLayout from "@/components/portal/PortalLayout";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { OptimizedImage } from "@/components/ui/Picture";
import { cn } from "@/lib/utils";
import { usePageTitle } from "@/hooks/usePageTitle";

/**
 * Free Tools — foundation wave.
 *
 * The index renders a card grid of every planned free tool. Live tools
 * (Schema, FAQ, Hours, Trust Badges) show a real Playwright-rendered
 * preview PNG generated by `scripts/generate-free-tool-previews.ts`.
 * Coming-soon cards keep the lucide icon-only treatment.
 *
 * This page is read-only — no editable form fields, so it lives on the
 * scripts/copilot-form-exempt.txt list.
 */

type ToolStatus = "available" | "coming-soon";

interface Tool {
  slug: string;
  title: string;
  description: string;
  icon: React.ElementType;
  status: ToolStatus;
  href?: string;
  /** Static preview PNG generated by the previews:free-tools script. */
  previewImage?: string;
}

const TOOLS: Tool[] = [
  {
    slug: "schema",
    title: "Local Business Schema",
    description:
      "Generate Google-friendly JSON-LD markup. Paste once, ranks forever.",
    icon: FileCode2,
    status: "available",
    href: "/portal/free-tools/schema",
    previewImage: "/free-tools/previews/schema.png",
  },
  {
    slug: "faq",
    title: "FAQ Widget",
    description:
      "Embed a styled accordion of Q&As with SEO schema baked in.",
    icon: HelpCircle,
    status: "available",
    href: "/portal/free-tools/faq",
    previewImage: "/free-tools/previews/faq.png",
  },
  {
    slug: "hours",
    title: "Hours Block",
    description:
      "Drop-in business hours panel — auto-shows open/closed status.",
    icon: Clock,
    status: "available",
    href: "/portal/free-tools/hours",
    previewImage: "/free-tools/previews/hours.png",
  },
  {
    slug: "trust-badges",
    title: "Trust Badges",
    description:
      "Licensed, insured, BBB-style badges that build instant credibility.",
    icon: ShieldCheck,
    status: "available",
    href: "/portal/free-tools/trust-badges",
    previewImage: "/free-tools/previews/badges.png",
  },
  {
    slug: "service-area-map",
    title: "Service Area Map",
    description:
      "Embed a styled map of the postal codes you cover — no Google account needed.",
    icon: MapPin,
    status: "available",
    href: "/portal/free-tools/service-area",
    previewImage: "/free-tools/previews/service-area.png",
  },
  {
    slug: "callback",
    title: "Callback Request",
    description:
      "One-tap callback form + inbox — captures leads even when you're on the truck.",
    icon: PhoneCall,
    status: "available",
    href: "/portal/free-tools/callback",
    previewImage: "/free-tools/previews/callback.png",
  },
  {
    slug: "review-link",
    title: "Review Link + QR Card",
    description:
      "Star-rating gate at /r/{your-slug} routes happy customers to Google; private feedback for the rest. Printable QR card included.",
    icon: Star,
    status: "available",
    href: "/portal/free-tools/review-link",
    previewImage: "/free-tools/previews/review-link.png",
  },
];

export default function FreeToolsIndex() {
  usePageTitle("Free Tools");
  return (
    <PortalLayout breadcrumb="Free Tools">
      <div data-theme="light" className="space-y-6">
        <header>
          <h1 className="text-2xl font-bold text-gray-900 mb-1">Free Tools</h1>
          <p className="text-sm text-gray-600">
            Valuable add-ons for your site — yours to use, no upgrade required.
          </p>
        </header>
        <div
          className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 auto-rows-fr"
          data-testid="free-tools-grid"
        >
          {TOOLS.map((tool) => {
            const Icon = tool.icon;
            const available = tool.status === "available";
            return (
              <Card
                key={tool.slug}
                className={cn("relative", !available && "opacity-60")}
                data-testid={`free-tool-card-${tool.slug}`}
              >
                <CardContent className="p-5 flex flex-col h-full">
                  {tool.previewImage ? (
                    <OptimizedImage
                      src={tool.previewImage}
                      alt={`${tool.title} preview`}
                      width={400}
                      height={250}
                      className="w-full aspect-[16/10] object-cover rounded-md border border-gray-200 mb-3 bg-gray-50"
                      loading="lazy"
                      data-testid={`free-tool-preview-${tool.slug}`}
                    />
                  ) : (
                    <Icon
                      className="w-5 h-5 text-gray-400 absolute top-3 right-3"
                      aria-hidden="true"
                    />
                  )}
                  <h3 className="font-semibold text-gray-900 mb-1 pr-8">
                    {tool.title}
                  </h3>
                  <p className="text-sm text-gray-600 mb-4 flex-1">
                    {tool.description}
                  </p>
                  {available && tool.href ? (
                    /* DS rule 4 — one .btn-primary-premium per page. Index has
                       7 tool cards, so per-card CTAs use the plain outline
                       variant; the premium accent is reserved for the
                       primary action on each individual tool page. */
                    <Button asChild variant="outline" size="sm" className="self-start">
                      <Link href={tool.href}>Open</Link>
                    </Button>
                  ) : (
                    <span className="inline-block self-start text-xs px-2 py-1 rounded-md bg-gray-100 text-gray-600">
                      Coming soon
                    </span>
                  )}
                </CardContent>
              </Card>
            );
          })}
        </div>
      </div>
    </PortalLayout>
  );
}
