// PreviewPane — sticky live preview for the Elfsight-clone editor (Wave H1).
//
// Reuses the same `previewCalculatorData` shape as the legacy WizardCard (so
// the `__preview` strip server-side guard still applies). The placeholder
// `advanced` config is generated by `buildBlankPreviewConfig(layout)` — the
// header reads `business_name` directly from the calculator object, so the
// preview header updates live as the user types in the Build tab.
//
// Bezels: desktop = browser-chrome card, mobile = phone shell. Wave G's
// `qq-bezel` classes and ≤768px media rules apply unchanged.

import { useMemo } from 'react';
import QuoteWidget from '@/components/quote-widget/QuoteWidget';
import type { CalculatorData } from '@/components/quote-widget/types';
import { buildBlankPreviewConfig, type TemplateLayout } from '@shared/templatePresets';
import { platformTheme } from '@/theme/platformTheme';
import type { PreviewDevice } from './types';

const p = platformTheme;

interface Props {
  businessName: string;
  layout: TemplateLayout;
  device: PreviewDevice;
}

export default function PreviewPane({ businessName, layout, device }: Props) {
  // Synthetic CalculatorData (preview-only). `id: -1` mirrors the legacy
  // sentinel so any downstream code that branches on a real id still treats
  // this as a preview.
  const previewCalculatorData = useMemo<CalculatorData>(() => {
    const advanced = buildBlankPreviewConfig(layout, businessName);
    return {
      id: -1,
      slug: 'preview',
      business_name: businessName || 'Your Business',
      primary_color: p.colors.accent,
      pricing_config: { pricingType: 'hourly', unitName: 'hour', rate: 75, baseFee: 50 },
      calculator_settings: {
        calculator_type: 'estimate_only',
        ui_template: { template_id: 'classic_single' },
        advanced,
      },
    };
  }, [businessName, layout]);

  return (
    <div className="qq-preview-pane" data-testid="editor-preview-pane">
      <div className="qq-preview-stage">
        <div
          className="widget-scope"
          style={{
            width: '100%', padding: '8px 8px 28px', minHeight: 430,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}
        >
          {device === 'mobile' ? (
            <div
              data-testid="preview-bezel-mobile"
              className="qq-bezel qq-bezel--mobile"
              style={{
                width: '100%', maxWidth: 390, maxHeight: 780, flexShrink: 0, margin: '0 auto',
                background: 'linear-gradient(160deg, #1e293b, #0f172a)',
                borderRadius: 44, padding: '12px 10px', boxSizing: 'border-box',
                overflow: 'hidden', display: 'flex', flexDirection: 'column',
                boxShadow: '0 22px 48px rgba(15,23,42,0.30), inset 0 0 0 1px rgba(255,255,255,0.06)',
              }}
            >
              <div style={{ height: 5, width: 42, borderRadius: 3, background: 'rgba(255,255,255,0.22)', margin: '0 auto 9px', flexShrink: 0 }} />
              <div style={{ borderRadius: 34, overflow: 'auto', background: '#fff', flex: 1 }}>
                <QuoteWidget calculator={previewCalculatorData} isEmbed />
              </div>
            </div>
          ) : (
            <div
              data-testid="preview-bezel-desktop"
              className="qq-bezel qq-bezel--desktop"
              style={{
                width: '100%', maxWidth: 820, maxHeight: 640, margin: '0 auto',
                borderRadius: 16, overflow: 'hidden', background: '#fff',
                border: `1px solid ${p.colors.borderLight}`,
                display: 'flex', flexDirection: 'column',
                boxShadow: '0 20px 48px rgba(15,23,42,0.16), 0 2px 8px rgba(15,23,42,0.06)',
              }}
            >
              <div
                className="qq-bezel-chrome"
                style={{
                  display: 'flex', alignItems: 'center', gap: 7, flexShrink: 0,
                  padding: '9px 14px', background: '#fbfcfd',
                  borderBottom: `1px solid ${p.colors.borderLight}`,
                }}
              >
                <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#f87171' }} />
                <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#fbbf24' }} />
                <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#34d399' }} />
                <div
                  style={{
                    flex: 1, maxWidth: 300, margin: '0 auto', textAlign: 'center',
                    fontSize: 11, fontWeight: 500, color: p.colors.subtle,
                    background: '#fff', border: `1px solid ${p.colors.borderLight}`,
                    borderRadius: 999, padding: '3px 12px',
                    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
                  }}
                >
                  {(businessName || 'your-business').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 28)}.your-quote.net
                </div>
              </div>
              <div style={{ flex: 1, overflow: 'auto' }}>
                <QuoteWidget calculator={previewCalculatorData} isEmbed />
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
