// PreviewPane — sticky live preview for the Elfsight-clone editor (Wave H1).
//
// Reuses the same `previewCalculatorData` shape as the legacy WizardCard (so
// the `__preview` strip server-side guard still applies). The placeholder
// `advanced` config is generated by `buildBlankPreviewConfig(layout)` — the
// header reads `business_name` directly from the calculator object, so the
// preview header updates live as the user types in the Build tab.
//
// Bezels: desktop = browser-chrome card, mobile = phone shell. Wave G's
// `qq-bezel` classes and ≤768px media rules apply unchanged.
//
// Wave I (items b, c, f):
//  - The preview bezel container is a droppable target — drops from
//    AddFieldMenu append a new field of that type.
//  - Inside the bezel we mount <PreviewOverlay/> that draws per-field
//    selection rings + remove (−) icons, AND a "+ Add field" slot at the end
//    of the inputs list. The slot is itself a droppable target and clicking
//    it opens the AddFieldMenu (portaled, mobile bottom sheet).

import { useMemo, useRef } from 'react';
import { useDroppable } from '@dnd-kit/core';
import QuoteWidget from '@/components/quote-widget/QuoteWidget';
import type { CalculatorData } from '@/components/quote-widget/types';
import {
  buildBlankPreviewConfig,
  type TemplateLayout, type TemplateField, type TemplateCalculation,
} from '@shared/templatePresets';
import { platformTheme } from '@/theme/platformTheme';
import { useSelection } from './selection';
import { DND_CONTAINERS } from './dnd';
import PreviewOverlay from './PreviewOverlay';
import type {
  PreviewDevice, ShellHeader, ShellResults, ShellStyle,
  ShellSettings, ShellNumberFormat, PublicFieldType,
} from './types';
import { DEFAULT_SHELL_NUMBER_FORMAT } from './types';

const p = platformTheme;

interface Props {
  businessName: string;
  /** Wave J item 5 — business logo (data URL or null). Surfaces in the
   *  preview header alongside the business name. */
  logo?: string | null;
  layout: TemplateLayout;
  device: PreviewDevice;
  fields?: TemplateField[];
  calculations?: TemplateCalculation[];
  header?: ShellHeader;
  results?: ShellResults;
  resultCalcId?: string;
  style?: ShellStyle;
  settings?: ShellSettings;
  /** Wave I (f): remove a field from inside the preview overlay. */
  onRemoveField?: (fieldId: string) => void;
  /** Wave I (f): add a field via the in-preview +Add slot. */
  onAddField?: (publicType: PublicFieldType) => void;
}

function thousandsLiteral(sep: ShellNumberFormat['thousands']): ',' | ' ' | '' {
  return sep === 'comma' ? ',' : sep === 'space' ? ' ' : '';
}
function decimalLiteral(sep: ShellNumberFormat['decimal']): '.' | ',' {
  return sep === 'comma' ? ',' : '.';
}

export default function PreviewPane({
  businessName, logo, layout, device, fields, calculations,
  header, results, resultCalcId, style, settings,
  onRemoveField, onAddField,
}: Props) {
  const selection = useSelection();
  // Track which field came from the live shell list — only those get the
  // per-field decorators. Placeholder seed fields (when `fields` is undefined)
  // are left alone since we can't reorder/remove them via the shell.
  const shellFields = fields ?? [];

  const previewCalculatorData = useMemo<CalculatorData>(() => {
    const advanced = buildBlankPreviewConfig(layout, businessName);
    let merged = fields !== undefined ? { ...advanced, fields } : advanced;
    if (calculations && calculations.length > 0) {
      const stillHasHeadline = calculations.some((c) => c.name === merged.result_calc);
      merged = {
        ...merged,
        calculations,
        result_calc: stillHasHeadline ? merged.result_calc : calculations[calculations.length - 1].name,
      };
    }
    if (resultCalcId) {
      const hit = merged.calculations.find((c) => c.id === resultCalcId);
      if (hit) merged = { ...merged, result_calc: hit.name };
    }
    if (header) {
      const titleOverride = (header.title ?? '').trim();
      const subtitleOverride = (header.subtitle ?? '').trim();
      const mergedHeader = { ...(merged.header || { title: '', align: 'left' as const }) };
      if (titleOverride !== '') mergedHeader.title = header.title!;
      if (subtitleOverride !== '') mergedHeader.subtitle = header.subtitle;
      merged = { ...merged, header: mergedHeader };
    }
    if (results) {
      const headingOverride = (results.heading ?? '').trim();
      const footnoteOverride = (results.footnote ?? '').trim();
      const mergedResults = { ...(merged.results || {}) };
      if (headingOverride !== '') mergedResults.heading = results.heading;
      if (footnoteOverride !== '') mergedResults.footnote = results.footnote;
      merged = { ...merged, results: mergedResults };
    }
    if (style) {
      merged = {
        ...merged,
        style: { ...(merged.style ?? {}), ...style },
      };
    }
    {
      const nf = settings?.numberFormat ?? DEFAULT_SHELL_NUMBER_FORMAT;
      const numberFormat = {
        thousands: thousandsLiteral(nf.thousands),
        decimal: decimalLiteral(nf.decimal),
        currency: (nf.currency || 'USD').toUpperCase(),
      };
      merged = { ...merged, numberFormat };

      const cta = (settings?.ctaLabel ?? '').trim();
      if (cta !== '') {
        merged = {
          ...merged,
          results: { ...(merged.results ?? {}), cta_label: cta },
        };
      }
    }
    return {
      id: -1,
      slug: 'preview',
      business_name: businessName || 'Your Business',
      ...(logo ? { logo_url: logo } : {}),
      primary_color: p.colors.accent,
      pricing_config: { pricingType: 'hourly', unitName: 'hour', rate: 75, baseFee: 50 },
      calculator_settings: {
        calculator_type: 'estimate_only',
        ui_template: { template_id: 'classic_single' },
        advanced: merged,
      },
    };
  }, [businessName, logo, layout, fields, calculations, header, results, resultCalcId, style, settings]);

  // Droppable wrapper for item (b) — drag from AddFieldMenu onto the preview
  // bezel. `data.kind: 'preview-append'` so WizardShell's onDragEnd appends.
  const { setNodeRef: setDropNodeRef, isOver } = useDroppable({
    id: 'qq-dnd-preview-pane',
    data: { kind: 'preview-append' },
  });

  // Results / header selection (item c) — clicking these regions selects them.
  // The decorators sit inside the bezel container, on top of the QuoteWidget.
  const resultsSel = selection.isSelected({ kind: 'results', id: '__results' });
  const headerSel = selection.isSelected({ kind: 'header', id: '__header' });
  const resultsRegisterRef = selection.registerNode({ kind: 'results', id: '__results' }, 'preview');
  const headerRegisterRef = selection.registerNode({ kind: 'header', id: '__header' }, 'preview');
  const previewBezelRef = useRef<HTMLDivElement | null>(null);
  // The overlay is rendered inside this inner wrapper (the QuoteWidget host)
  // so coords are relative to it, not the bezel.
  const overlayHostRef = useRef<HTMLDivElement | null>(null);

  /** Combine the droppable setNodeRef and the bezel ref into one ref callback. */
  const setBezelRef = (el: HTMLDivElement | null) => {
    setDropNodeRef(el);
    previewBezelRef.current = el;
  };

  // Header and results regions overlay over the AdvancedCalculator. They're
  // identified by data-testid="advanced-title" and the result-panel container.
  // We attach click handlers via event delegation on the bezel.
  const onBezelClick = (e: React.MouseEvent) => {
    const target = e.target as HTMLElement;
    // If the user clicked a real input/button inside the widget, let it run.
    if (target.closest('input, select, button, textarea')) return;
    // Results region — anywhere inside the result panel.
    const resultBlock = target.closest('[data-testid="result-output"]')
      || target.closest('[data-testid="advanced-result"]')
      || target.closest('.qq-result-block');
    if (resultBlock) {
      selection.select({ kind: 'results', id: '__results' });
      return;
    }
    // Header region.
    const headerBlock = target.closest('[data-testid="advanced-title"]')?.closest('div');
    if (headerBlock) {
      selection.select({ kind: 'header', id: '__header' });
      return;
    }
  };

  return (
    <div className="qq-preview-pane" data-testid="editor-preview-pane">
      <div className="qq-preview-stage">
        <div
          className="widget-scope"
          style={{
            width: '100%', padding: '8px 8px 28px', minHeight: 430,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}
        >
          {device === 'mobile' ? (
            <div
              ref={setBezelRef}
              data-testid="preview-bezel-mobile"
              className={`qq-bezel qq-bezel--mobile${isOver ? ' is-drop-target' : ''}`}
              onClick={onBezelClick}
              style={{
                position: 'relative',
                width: '100%', maxWidth: 390, maxHeight: 780, flexShrink: 0, margin: '0 auto',
                background: 'linear-gradient(160deg, #1e293b, #0f172a)',
                borderRadius: 44, padding: '12px 10px', boxSizing: 'border-box',
                overflow: 'hidden', display: 'flex', flexDirection: 'column',
                boxShadow: '0 22px 48px rgba(15,23,42,0.30), inset 0 0 0 1px rgba(255,255,255,0.06)',
              }}
            >
              <div style={{ height: 5, width: 42, borderRadius: 3, background: 'rgba(255,255,255,0.22)', margin: '0 auto 9px', flexShrink: 0 }} />
              <div ref={overlayHostRef} style={{ borderRadius: 34, overflow: 'auto', background: '#fff', flex: 1, position: 'relative' }}>
                <QuoteWidget calculator={previewCalculatorData} isEmbed />
                {shellFields.length > 0 && onRemoveField && onAddField && (
                  <PreviewOverlay
                    fields={shellFields}
                    containerRef={overlayHostRef as React.RefObject<HTMLDivElement>}
                    onRemoveField={onRemoveField}
                    onAddField={onAddField}
                  />
                )}
                {resultsSel && (
                  <div ref={resultsRegisterRef} data-selected-in-preview="" data-testid="preview-selected-results" style={{ display: 'none' }} />
                )}
                {headerSel && (
                  <div ref={headerRegisterRef} data-selected-in-preview="" data-testid="preview-selected-header" style={{ display: 'none' }} />
                )}
              </div>
            </div>
          ) : (
            <div
              ref={setBezelRef}
              data-testid="preview-bezel-desktop"
              className={`qq-bezel qq-bezel--desktop${isOver ? ' is-drop-target' : ''}`}
              onClick={onBezelClick}
              style={{
                position: 'relative',
                width: '100%', maxWidth: 820, maxHeight: 640, margin: '0 auto',
                borderRadius: 16, overflow: 'hidden', background: '#fff',
                border: `1px solid ${p.colors.borderLight}`,
                display: 'flex', flexDirection: 'column',
                boxShadow: '0 20px 48px rgba(15,23,42,0.16), 0 2px 8px rgba(15,23,42,0.06)',
              }}
            >
              <div
                className="qq-bezel-chrome"
                style={{
                  display: 'flex', alignItems: 'center', gap: 7, flexShrink: 0,
                  padding: '9px 14px', background: '#fbfcfd',
                  borderBottom: `1px solid ${p.colors.borderLight}`,
                }}
              >
                <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#f87171' }} />
                <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#fbbf24' }} />
                <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#34d399' }} />
                <div
                  style={{
                    flex: 1, maxWidth: 300, margin: '0 auto', textAlign: 'center',
                    fontSize: 11, fontWeight: 500, color: p.colors.subtle,
                    background: '#fff', border: `1px solid ${p.colors.borderLight}`,
                    borderRadius: 999, padding: '3px 12px',
                    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
                  }}
                >
                  {(businessName || 'your-business').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 28)}.your-quote.net
                </div>
              </div>
              <div ref={overlayHostRef} style={{ flex: 1, overflow: 'auto', position: 'relative' }}>
                <QuoteWidget calculator={previewCalculatorData} isEmbed />
                {shellFields.length > 0 && onRemoveField && onAddField && (
                  <PreviewOverlay
                    fields={shellFields}
                    containerRef={overlayHostRef as React.RefObject<HTMLDivElement>}
                    onRemoveField={onRemoveField}
                    onAddField={onAddField}
                  />
                )}
                {resultsSel && (
                  <div ref={resultsRegisterRef} data-selected-in-preview="" data-testid="preview-selected-results" style={{ display: 'none' }} />
                )}
                {headerSel && (
                  <div ref={headerRegisterRef} data-selected-in-preview="" data-testid="preview-selected-header" style={{ display: 'none' }} />
                )}
              </div>
            </div>
          )}
        </div>
      </div>
      <style>{`
        .qq-bezel.is-drop-target {
          outline: 3px dashed ${p.colors.accent};
          outline-offset: -3px;
        }
      `}</style>
    </div>
  );
}

// Re-export to satisfy non-type consumers in stable order — nothing external.
export { DND_CONTAINERS };
