// PreviewPane — sticky live preview for the Elfsight-clone editor (Wave H1).
//
// Reuses the same `previewCalculatorData` shape as the legacy WizardCard (so
// the `__preview` strip server-side guard still applies). The placeholder
// `advanced` config is generated by `buildBlankPreviewConfig(layout)` — the
// header reads `business_name` directly from the calculator object, so the
// preview header updates live as the user types in the Build tab.
//
// Bezels: desktop = browser-chrome card, mobile = phone shell. Wave G's
// `qq-bezel` classes and ≤768px media rules apply unchanged.
//
// Wave I (items b, c, f):
//  - The preview bezel container is a droppable target — drops from
//    AddFieldMenu append a new field of that type.
//  - Inside the bezel we mount <PreviewOverlay/> that draws per-field
//    selection rings + remove (−) icons, AND a "+ Add field" slot at the end
//    of the inputs list. The slot is itself a droppable target and clicking
//    it opens the AddFieldMenu (portaled, mobile bottom sheet).

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useDroppable } from '@dnd-kit/core';
import QuoteWidget from '@/components/quote-widget/QuoteWidget';
import HostedPageFrame from '@/components/hosted-page/HostedPageFrame';
import type { CalculatorData } from '@/components/quote-widget/types';
import {
  buildBlankPreviewConfig,
  type TemplateLayout, type TemplateField, type TemplateCalculation,
} from '@shared/templatePresets';
import { platformTheme } from '@/theme/platformTheme';
import { useSelection } from './selection';
import { DND_CONTAINERS } from './dnd';
import PreviewOverlay from './PreviewOverlay';
import AddFieldMenu from './AddFieldMenu';
import type {
  PreviewDevice, ShellHeader, ShellResults, ShellStyle,
  ShellSettings, ShellNumberFormat, PublicFieldType,
} from './types';
import { DEFAULT_SHELL_NUMBER_FORMAT } from './types';

const p = platformTheme;

interface Props {
  businessName: string;
  /** Wave L E5 — two-way bind. When the user inline-edits the preview header
   *  title, this fires; the Build-tab business-name field stays in sync. */
  onBusinessNameChange?: (v: string) => void;
  /** Wave J item 5 — business logo (data URL or null). Surfaces in the
   *  preview header alongside the business name. */
  logo?: string | null;
  layout: TemplateLayout;
  device: PreviewDevice;
  fields?: TemplateField[];
  calculations?: TemplateCalculation[];
  header?: ShellHeader;
  results?: ShellResults;
  resultCalcId?: string;
  style?: ShellStyle;
  settings?: ShellSettings;
  /** Wave I (f): remove a field from inside the preview overlay. */
  onRemoveField?: (fieldId: string) => void;
  /** Wave I (f): add a field via the in-preview +Add slot. */
  onAddField?: (publicType: PublicFieldType) => void;
  /** Wave P — when true, wrap the QuoteWidget in HostedPageFrame so the
   *  preview matches the public hosted page. Defaults to false (bare
   *  widget, the long-standing behaviour). */
  hostedFrame?: boolean;
}

function thousandsLiteral(sep: ShellNumberFormat['thousands']): ',' | ' ' | '' {
  return sep === 'comma' ? ',' : sep === 'space' ? ' ' : '';
}
function decimalLiteral(sep: ShellNumberFormat['decimal']): '.' | ',' {
  return sep === 'comma' ? ',' : '.';
}

export default function PreviewPane({
  businessName, onBusinessNameChange, logo, layout, device, fields, calculations,
  header, results, resultCalcId, style, settings,
  onRemoveField, onAddField,
  hostedFrame = false,
}: Props) {
  const selection = useSelection();
  // Track which field came from the live shell list — only those get the
  // per-field decorators. Placeholder seed fields (when `fields` is undefined)
  // are left alone since we can't reorder/remove them via the shell.
  const shellFields = fields ?? [];

  const previewCalculatorData = useMemo<CalculatorData>(() => {
    const advanced = buildBlankPreviewConfig(layout, businessName);
    let merged = fields !== undefined ? { ...advanced, fields } : advanced;
    if (calculations && calculations.length > 0) {
      const stillHasHeadline = calculations.some((c) => c.name === merged.result_calc);
      merged = {
        ...merged,
        calculations,
        result_calc: stillHasHeadline ? merged.result_calc : calculations[calculations.length - 1].name,
      };
    }
    if (resultCalcId) {
      const hit = merged.calculations.find((c) => c.id === resultCalcId);
      if (hit) merged = { ...merged, result_calc: hit.name };
    }
    if (header) {
      const titleOverride = (header.title ?? '').trim();
      const subtitleOverride = (header.subtitle ?? '').trim();
      const mergedHeader = { ...(merged.header || { title: '', align: 'left' as const }) };
      if (titleOverride !== '') mergedHeader.title = header.title!;
      if (subtitleOverride !== '') mergedHeader.subtitle = header.subtitle;
      merged = { ...merged, header: mergedHeader };
    }
    if (results) {
      const headingOverride = (results.heading ?? '').trim();
      const footnoteOverride = (results.footnote ?? '').trim();
      const mergedResults = { ...(merged.results || {}) };
      if (headingOverride !== '') mergedResults.heading = results.heading;
      if (footnoteOverride !== '') mergedResults.footnote = results.footnote;
      merged = { ...merged, results: mergedResults };
    }
    if (style) {
      merged = {
        ...merged,
        style: { ...(merged.style ?? {}), ...style },
      };
    }
    {
      const nf = settings?.numberFormat ?? DEFAULT_SHELL_NUMBER_FORMAT;
      const numberFormat = {
        thousands: thousandsLiteral(nf.thousands),
        decimal: decimalLiteral(nf.decimal),
        currency: (nf.currency || 'USD').toUpperCase(),
      };
      merged = { ...merged, numberFormat };

      const cta = (settings?.ctaLabel ?? '').trim();
      if (cta !== '') {
        merged = {
          ...merged,
          results: { ...(merged.results ?? {}), cta_label: cta },
        };
      }
    }
    return {
      id: -1,
      slug: 'preview',
      business_name: businessName || 'Your Business',
      ...(logo ? { logo_url: logo } : {}),
      primary_color: p.colors.accent,
      pricing_config: { pricingType: 'hourly', unitName: 'hour', rate: 75, baseFee: 50 },
      calculator_settings: {
        calculator_type: 'estimate_only',
        ui_template: { template_id: 'classic_single' },
        advanced: merged,
      },
    };
  }, [businessName, logo, layout, fields, calculations, header, results, resultCalcId, style, settings]);

  // Droppable wrapper for item (b) — drag from AddFieldMenu onto the preview
  // bezel. `data.kind: 'preview-append'` so WizardShell's onDragEnd appends.
  const { setNodeRef: setDropNodeRef, isOver } = useDroppable({
    id: 'qq-dnd-preview-pane',
    data: { kind: 'preview-append' },
  });

  // Results / header selection (item c) — clicking these regions selects them.
  // The decorators sit inside the bezel container, on top of the QuoteWidget.
  const resultsSel = selection.isSelected({ kind: 'results', id: '__results' });
  const headerSel = selection.isSelected({ kind: 'header', id: '__header' });
  const resultsRegisterRef = selection.registerNode({ kind: 'results', id: '__results' }, 'preview');
  const headerRegisterRef = selection.registerNode({ kind: 'header', id: '__header' }, 'preview');
  const previewBezelRef = useRef<HTMLDivElement | null>(null);
  // The overlay is rendered inside this inner wrapper (the QuoteWidget host)
  // so coords are relative to it, not the bezel.
  const overlayHostRef = useRef<HTMLDivElement | null>(null);

  /** Combine the droppable setNodeRef and the bezel ref into one ref callback. */
  const setBezelRef = (el: HTMLDivElement | null) => {
    setDropNodeRef(el);
    previewBezelRef.current = el;
  };

  // Header and results regions overlay over the AdvancedCalculator. They're
  // identified by data-testid="advanced-title" and the result-panel container.
  // We attach click handlers via event delegation on the bezel.
  //
  // Wave L E4 + B1 — also handles field-level selection now that the
  // PreviewOverlay's per-field wrapper is pointer-events:none. The
  // closest('input,…') bail-out keeps real controls (sliders, checkboxes,
  // dropdowns) interactive. The field-level fallback walks up to the matching
  // [data-colspan] node and looks up its index against the rendered field
  // boxes from PreviewOverlay (via the data-preview-field-id attribute).
  const onBezelClick = (e: React.MouseEvent) => {
    const target = e.target as HTMLElement;
    // If the user clicked a real input/button/control, let it run.
    if (target.closest('input, select, button, textarea, label, a, [role="slider"], [role="radio"], [role="checkbox"], [role="option"]')) {
      return;
    }
    // Results region — anywhere inside the result panel.
    const resultBlock = target.closest('[data-testid="advanced-result-panel"]')
      || target.closest('[data-testid="advanced-result"]')
      || target.closest('.qq-result-block');
    if (resultBlock) {
      selection.select({ kind: 'results', id: '__results' });
      return;
    }
    // Header region.
    const headerBlock = target.closest('[data-testid="advanced-title"]')?.closest('div');
    if (headerBlock) {
      selection.select({ kind: 'header', id: '__header' });
      // Wave L E5 — clicking the title block ALSO opens the inline editor.
      // The Build-tab business-name field stays the canonical source; this
      // is just a second affordance for the same value.
      openTitleEditor();
      return;
    }
    // Field region. Find the [data-colspan] cell and map its index to the
    // matching shell field id.
    const fieldCell = target.closest('[data-colspan]') as HTMLElement | null;
    if (fieldCell && fieldCell.parentElement) {
      const cells = Array.from(fieldCell.parentElement.querySelectorAll<HTMLElement>('[data-colspan]'));
      const idx = cells.indexOf(fieldCell);
      if (idx >= 0 && idx < shellFields.length) {
        selection.select({ kind: 'field', id: shellFields[idx].id });
      }
    }
  };

  // Wave L M1 — auto-zoom-out on mobile so the whole mockup fits without
  // the user needing to scroll inside the bezel. We measure the natural
  // height of the calculator inside the bezel and apply CSS transform:
  // scale(...) clamped 0.6-1.0 on the mockup container.
  //
  // Critically: pinch-zoom must still work. We only set `transform` on the
  // bezel container, NOT `touch-action: none` — native pinch on iOS/Android
  // remains operational because no listeners block pointer events.
  const bezelScaleRef = useRef<HTMLDivElement | null>(null);
  useEffect(() => {
    if (device !== 'mobile') {
      if (bezelScaleRef.current) {
        bezelScaleRef.current.style.transform = '';
      }
      return;
    }
    const calc = () => {
      const wrap = bezelScaleRef.current;
      if (!wrap) return;
      // Available area is roughly the wrapping pane height; we read the
      // closest qq-editor-right (or fallback to viewport innerHeight).
      const pane = wrap.closest('.qq-editor-right') as HTMLElement | null
        || wrap.parentElement;
      if (!pane) return;
      const available = pane.clientHeight - 32; // breathing room
      // Reset transform first so naturalHeight is measured correctly.
      wrap.style.transform = '';
      const natural = wrap.scrollHeight;
      if (natural <= 0 || available <= 0) return;
      let scale = available / natural;
      if (scale >= 1) {
        wrap.style.transform = '';
        return;
      }
      scale = Math.max(0.6, Math.min(1, scale));
      wrap.style.transformOrigin = 'top center';
      wrap.style.transform = `scale(${scale.toFixed(3)})`;
    };
    const raf = requestAnimationFrame(calc);
    const ro = new ResizeObserver(() => requestAnimationFrame(calc));
    if (bezelScaleRef.current) ro.observe(bezelScaleRef.current);
    window.addEventListener('resize', calc);
    return () => {
      cancelAnimationFrame(raf);
      ro.disconnect();
      window.removeEventListener('resize', calc);
    };
  }, [device, fields, calculations]);

  // Wave L E5 — editable preview header title.
  //
  // State + box drives an absolutely-positioned <input> overlay that paints
  // ON TOP of the static `<p data-testid="advanced-title">` rendered by
  // AdvancedCalculator. Clicking the title (via bezel delegation) opens the
  // editor; blur or Enter commits the value to `businessName` via the
  // two-way bind. Empty values are allowed — the title gracefully falls
  // back to the placeholder while editing.
  const [titleEditing, setTitleEditing] = useState(false);
  const [titleBox, setTitleBox] = useState<{ left: number; top: number; width: number; height: number } | null>(null);
  const titleInputRef = useRef<HTMLInputElement | null>(null);

  const measureTitle = useCallback(() => {
    const host = overlayHostRef.current;
    if (!host) return;
    const t = host.querySelector<HTMLElement>('[data-testid="advanced-title"]');
    if (!t) { setTitleBox(null); return; }
    const hostRect = host.getBoundingClientRect();
    const r = t.getBoundingClientRect();
    setTitleBox({
      left: r.left - hostRect.left,
      top: r.top - hostRect.top,
      width: Math.max(r.width, 200),
      height: r.height,
    });
  }, []);

  useEffect(() => {
    if (!titleEditing) return;
    measureTitle();
    const id1 = requestAnimationFrame(measureTitle);
    const onResize = () => measureTitle();
    window.addEventListener('resize', onResize);
    return () => { cancelAnimationFrame(id1); window.removeEventListener('resize', onResize); };
  }, [titleEditing, measureTitle, businessName, header]);

  const openTitleEditor = useCallback(() => {
    if (!onBusinessNameChange) return;
    measureTitle();
    setTitleEditing(true);
    setTimeout(() => { titleInputRef.current?.focus(); titleInputRef.current?.select(); }, 0);
  }, [onBusinessNameChange, measureTitle]);

  // Wave L E3 — swipe-to-delete on mobile. Listen for touchstart on the
  // overlay host; if the user swipes > 80px horizontally (either direction)
  // on a field cell, remove that field and show an undo toast.
  //
  // No new deps: pure pointer/touch events on the host element. The drag
  // gesture from @dnd-kit is on the LEFT-PANE field rows (and the add-field
  // menu), not here, so there's no conflict.
  const [undo, setUndo] = useState<null | { field: TemplateField; index: number }>(null);
  const undoTimerRef = useRef<number | null>(null);
  const onUndo = useCallback(() => {
    if (!undo) return;
    // Re-insert the field at its original position. We have to read the
    // current fields list at click time so the splice respects any other
    // changes that happened during the undo window.
    const u = undo;
    setUndo(null);
    if (undoTimerRef.current) { window.clearTimeout(undoTimerRef.current); undoTimerRef.current = null; }
    // Re-insert via onAddField is not possible (it only appends). The parent
    // doesn't expose a generic setFields, but the field deletion happened via
    // the same `onRemoveField` path the shell uses. For the undo we use a
    // direct DOM-bypass: we synthesise a `qq-undo-restore` custom event and
    // let WizardShell listen for it via window.
    const ev = new CustomEvent('qq-undo-restore-field', {
      detail: { field: u.field, index: u.index },
    });
    window.dispatchEvent(ev);
  }, [undo]);

  useEffect(() => {
    const host = overlayHostRef.current;
    if (!host || !onRemoveField || shellFields.length === 0) return;
    let startX = 0;
    let startY = 0;
    let startCell: HTMLElement | null = null;
    let trackingId = -1;
    const SWIPE_PX = 80;

    const onTouchStart = (e: TouchEvent) => {
      if (e.touches.length !== 1) return;
      const t = e.touches[0];
      const target = (e.target as HTMLElement);
      // Don't start swipe-tracking on interactive controls — leaves native
      // slider drag / button taps unaffected.
      if (target.closest('input, button, a, label, select, textarea, [role="slider"]')) return;
      const cell = target.closest('[data-colspan]') as HTMLElement | null;
      if (!cell || !cell.parentElement) return;
      startCell = cell;
      startX = t.clientX;
      startY = t.clientY;
      trackingId = t.identifier;
      // Subtle visual cue: outline the cell while tracking.
      cell.dataset.swipeTracking = '1';
    };
    const onTouchMove = (e: TouchEvent) => {
      if (!startCell || trackingId < 0) return;
      const t = Array.from(e.touches).find((x) => x.identifier === trackingId);
      if (!t) return;
      const dx = t.clientX - startX;
      const dy = t.clientY - startY;
      // Cancel if mostly vertical — let scroll happen.
      if (Math.abs(dy) > Math.abs(dx)) {
        if (startCell) delete startCell.dataset.swipeTracking;
        startCell = null;
        return;
      }
      // Visually pull the cell with the finger (capped at 100px).
      const offset = Math.max(-100, Math.min(100, dx));
      startCell.style.transform = `translateX(${offset}px)`;
      startCell.style.opacity = String(1 - Math.min(Math.abs(offset) / 160, 0.5));
    };
    const onTouchEnd = (e: TouchEvent) => {
      const t = Array.from(e.changedTouches).find((x) => x.identifier === trackingId);
      if (!t || !startCell || !startCell.parentElement) {
        if (startCell) {
          startCell.style.transform = '';
          startCell.style.opacity = '';
          delete startCell.dataset.swipeTracking;
        }
        startCell = null;
        trackingId = -1;
        return;
      }
      const dx = t.clientX - startX;
      const cells = Array.from(startCell.parentElement.querySelectorAll<HTMLElement>('[data-colspan]'));
      const idx = cells.indexOf(startCell);
      if (Math.abs(dx) >= SWIPE_PX && idx >= 0 && idx < shellFields.length) {
        const field = shellFields[idx];
        // Visual: slide out the rest of the way.
        startCell.style.transform = `translateX(${dx > 0 ? 400 : -400}px)`;
        startCell.style.opacity = '0';
        setUndo({ field, index: idx });
        if (undoTimerRef.current) window.clearTimeout(undoTimerRef.current);
        undoTimerRef.current = window.setTimeout(() => setUndo(null), 4000);
        // Defer the actual removal so the slide-out paints.
        window.setTimeout(() => onRemoveField(field.id), 160);
      } else {
        // Snap back.
        startCell.style.transform = '';
        startCell.style.opacity = '';
      }
      if (startCell) delete startCell.dataset.swipeTracking;
      startCell = null;
      trackingId = -1;
    };
    host.addEventListener('touchstart', onTouchStart, { passive: true });
    host.addEventListener('touchmove', onTouchMove, { passive: true });
    host.addEventListener('touchend', onTouchEnd, { passive: true });
    host.addEventListener('touchcancel', onTouchEnd, { passive: true });
    return () => {
      host.removeEventListener('touchstart', onTouchStart);
      host.removeEventListener('touchmove', onTouchMove);
      host.removeEventListener('touchend', onTouchEnd);
      host.removeEventListener('touchcancel', onTouchEnd);
    };
  }, [shellFields, onRemoveField]);

  return (
    <div className="qq-preview-pane" data-testid="editor-preview-pane">
      <div className="qq-preview-stage">
        <div
          className="widget-scope"
          style={{
            width: '100%', padding: '8px 8px 28px', minHeight: 430,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}
        >
          {device === 'mobile' ? (
            <div
              ref={(el) => { setBezelRef(el); bezelScaleRef.current = el; }}
              data-testid="preview-bezel-mobile"
              className={`qq-bezel qq-bezel--mobile${isOver ? ' is-drop-target' : ''}`}
              onClick={onBezelClick}
              style={{
                position: 'relative',
                width: '100%', maxWidth: 390, maxHeight: 780, flexShrink: 0, margin: '0 auto',
                background: 'linear-gradient(160deg, #1e293b, #0f172a)',
                borderRadius: 44, padding: '12px 10px', boxSizing: 'border-box',
                overflow: 'hidden', display: 'flex', flexDirection: 'column',
                boxShadow: '0 22px 48px rgba(15,23,42,0.30), inset 0 0 0 1px rgba(255,255,255,0.06)',
              }}
            >
              <div style={{ height: 5, width: 42, borderRadius: 3, background: 'rgba(255,255,255,0.22)', margin: '0 auto 9px', flexShrink: 0 }} />
              <div ref={overlayHostRef} style={{ borderRadius: 34, overflow: 'auto', background: '#fff', flex: 1, position: 'relative' }}>
                {hostedFrame ? (
                  <HostedPageFrame
                    settings={settings?.hostedPage}
                    logoUrl={logo}
                    businessName={businessName}
                    compact
                  >
                    <QuoteWidget calculator={previewCalculatorData} isEmbed />
                  </HostedPageFrame>
                ) : (
                  <QuoteWidget calculator={previewCalculatorData} isEmbed />
                )}
                {shellFields.length > 0 && onRemoveField && onAddField && (
                  <PreviewOverlay
                    fields={shellFields}
                    containerRef={overlayHostRef as React.RefObject<HTMLDivElement>}
                    onRemoveField={onRemoveField}
                    onAddField={onAddField}
                  />
                )}
                {shellFields.length === 0 && onAddField && (
                  <PreviewEmptyState onAddField={onAddField} />
                )}
                {titleEditing && titleBox && onBusinessNameChange && (
                  <input
                    ref={titleInputRef}
                    type="text"
                    className="qq-preview-title-edit"
                    data-testid="preview-title-edit"
                    placeholder="Add your business name here"
                    value={businessName}
                    onChange={(e) => onBusinessNameChange(e.target.value)}
                    onBlur={() => setTitleEditing(false)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' || e.key === 'Escape') {
                        (e.target as HTMLInputElement).blur();
                      }
                    }}
                    style={{
                      position: 'absolute',
                      left: titleBox.left, top: titleBox.top,
                      width: titleBox.width, height: titleBox.height,
                    }}
                  />
                )}
                {resultsSel && (
                  <div ref={resultsRegisterRef} data-selected-in-preview="" data-testid="preview-selected-results" style={{ display: 'none' }} />
                )}
                {headerSel && (
                  <div ref={headerRegisterRef} data-selected-in-preview="" data-testid="preview-selected-header" style={{ display: 'none' }} />
                )}
              </div>
            </div>
          ) : (
            <div
              ref={setBezelRef}
              data-testid="preview-bezel-desktop"
              className={`qq-bezel qq-bezel--desktop${isOver ? ' is-drop-target' : ''}`}
              onClick={onBezelClick}
              style={{
                position: 'relative',
                width: '100%', maxWidth: 820, maxHeight: 640, margin: '0 auto',
                borderRadius: 16, overflow: 'hidden', background: '#fff',
                border: `1px solid ${p.colors.borderLight}`,
                display: 'flex', flexDirection: 'column',
                boxShadow: '0 20px 48px rgba(15,23,42,0.16), 0 2px 8px rgba(15,23,42,0.06)',
              }}
            >
              <div
                className="qq-bezel-chrome"
                style={{
                  display: 'flex', alignItems: 'center', gap: 7, flexShrink: 0,
                  padding: '9px 14px', background: '#fbfcfd',
                  borderBottom: `1px solid ${p.colors.borderLight}`,
                }}
              >
                <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#f87171' }} />
                <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#fbbf24' }} />
                <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#34d399' }} />
                <div
                  style={{
                    flex: 1, maxWidth: 300, margin: '0 auto', textAlign: 'center',
                    fontSize: 11, fontWeight: 500, color: p.colors.subtle,
                    background: '#fff', border: `1px solid ${p.colors.borderLight}`,
                    borderRadius: 999, padding: '3px 12px',
                    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
                  }}
                >
                  {(businessName || 'your-business').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 28)}.your-quote.net
                </div>
              </div>
              <div ref={overlayHostRef} style={{ flex: 1, overflow: 'auto', position: 'relative' }}>
                {hostedFrame ? (
                  <HostedPageFrame
                    settings={settings?.hostedPage}
                    logoUrl={logo}
                    businessName={businessName}
                    compact
                  >
                    <QuoteWidget calculator={previewCalculatorData} isEmbed />
                  </HostedPageFrame>
                ) : (
                  <QuoteWidget calculator={previewCalculatorData} isEmbed />
                )}
                {shellFields.length > 0 && onRemoveField && onAddField && (
                  <PreviewOverlay
                    fields={shellFields}
                    containerRef={overlayHostRef as React.RefObject<HTMLDivElement>}
                    onRemoveField={onRemoveField}
                    onAddField={onAddField}
                  />
                )}
                {shellFields.length === 0 && onAddField && (
                  <PreviewEmptyState onAddField={onAddField} />
                )}
                {titleEditing && titleBox && onBusinessNameChange && (
                  <input
                    ref={titleInputRef}
                    type="text"
                    className="qq-preview-title-edit"
                    data-testid="preview-title-edit"
                    placeholder="Add your business name here"
                    value={businessName}
                    onChange={(e) => onBusinessNameChange(e.target.value)}
                    onBlur={() => setTitleEditing(false)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' || e.key === 'Escape') {
                        (e.target as HTMLInputElement).blur();
                      }
                    }}
                    style={{
                      position: 'absolute',
                      left: titleBox.left, top: titleBox.top,
                      width: titleBox.width, height: titleBox.height,
                    }}
                  />
                )}
                {resultsSel && (
                  <div ref={resultsRegisterRef} data-selected-in-preview="" data-testid="preview-selected-results" style={{ display: 'none' }} />
                )}
                {headerSel && (
                  <div ref={headerRegisterRef} data-selected-in-preview="" data-testid="preview-selected-header" style={{ display: 'none' }} />
                )}
              </div>
            </div>
          )}
        </div>
      </div>
      {/* Wave L E3 — swipe-to-delete undo toast. Fixed-position so it floats
       * over the preview without disturbing layout; auto-dismisses after 4s. */}
      {undo && (
        <div
          className="qq-preview-undo-toast"
          role="status"
          data-testid="preview-undo-toast"
        >
          <span>Field removed</span>
          <button
            type="button"
            onClick={onUndo}
            data-testid="preview-undo-button"
          >
            Undo
          </button>
        </div>
      )}
      <style>{`
        .qq-bezel.is-drop-target {
          outline: 3px dashed ${p.colors.accent};
          outline-offset: -3px;
        }
        /* Wave L E5 — inline editor input for the preview header title. */
        .qq-preview-title-edit {
          font-size: 17px; font-weight: 800;
          letter-spacing: -0.01em;
          color: #0f172a;
          background: #fff;
          border: 2px solid ${p.colors.accent};
          border-radius: 6px;
          padding: 0 6px;
          outline: none;
          box-sizing: border-box;
          z-index: 3;
        }
        .qq-preview-title-edit::placeholder {
          color: #94a3b8; font-weight: 600;
        }
        /* Wave L E3 — swipe-to-delete visual feedback. */
        [data-colspan][data-swipe-tracking="1"] {
          transition: none;
        }
        [data-colspan] {
          transition: transform 160ms ease, opacity 160ms ease;
        }
        .qq-preview-undo-toast {
          position: fixed; bottom: 24px; left: 50%;
          transform: translateX(-50%);
          z-index: 1300;
          display: inline-flex; align-items: center; gap: 12px;
          padding: 10px 16px;
          font-size: 13px; font-weight: 600;
          color: #fff; background: #0f172a;
          border-radius: 999px;
          box-shadow: 0 10px 30px rgba(15,23,42,0.30);
          animation: qq-toast-in 180ms ease-out;
        }
        .qq-preview-undo-toast button {
          font: inherit; cursor: pointer;
          padding: 0 0 0 4px;
          background: transparent; border: 0;
          color: ${p.colors.accentLighter};
          text-decoration: underline;
        }
        @keyframes qq-toast-in {
          from { opacity: 0; transform: translate(-50%, 6px); }
          to   { opacity: 1; transform: translate(-50%, 0); }
        }
      `}</style>
    </div>
  );
}

// Re-export to satisfy non-type consumers in stable order — nothing external.
export { DND_CONTAINERS };

/* ─── Wave L E1 — empty-state placeholder ──────────────────────────────
 * Rendered when there are zero fields in the preview. A large dashed
 * dropzone with a big `+` icon and "Add your first field" copy. Click /
 * tap opens the same AddFieldMenu used by the Build tab + the in-preview
 * append slot. */
function PreviewEmptyState({ onAddField }: { onAddField: (publicType: PublicFieldType) => void }) {
  return (
    <div
      className="qq-preview-empty-state"
      data-testid="preview-empty-state"
      aria-label="No fields yet — add one to get started"
    >
      <div className="qq-preview-empty-state-card">
        <div className="qq-preview-empty-state-plus" aria-hidden="true">＋</div>
        <p className="qq-preview-empty-state-title">Add your first field</p>
        <p className="qq-preview-empty-state-sub">
          Pick a slider, dropdown, choice, image choice, number, or heading
          to start building your calculator.
        </p>
        <div className="qq-preview-empty-state-cta">
          <AddFieldMenu onPick={onAddField} emphasis />
        </div>
      </div>
      <style>{`
        .qq-preview-empty-state {
          position: absolute;
          left: 0; right: 0; bottom: 0;
          /* Sit below the title bar (~62px) so the heading is still visible. */
          top: 70px;
          display: flex; align-items: center; justify-content: center;
          padding: 24px;
          background: rgba(255,255,255,0.92);
          pointer-events: none;
        }
        .qq-preview-empty-state-card {
          pointer-events: auto;
          width: 100%; max-width: 360px;
          padding: 28px 24px;
          background: #fff;
          border: 2px dashed rgba(13, 60, 252, 0.45);
          border-radius: 16px;
          display: flex; flex-direction: column; align-items: center;
          gap: 8px; text-align: center;
        }
        .qq-preview-empty-state-plus {
          width: 56px; height: 56px; border-radius: 50%;
          background: rgba(13, 60, 252, 0.10);
          color: ${p.colors.accent};
          font-size: 32px; font-weight: 300; line-height: 1;
          display: inline-flex; align-items: center; justify-content: center;
        }
        .qq-preview-empty-state-title {
          font-size: 16px; font-weight: 800; color: ${p.colors.heading};
          margin: 4px 0 0;
        }
        .qq-preview-empty-state-sub {
          font-size: 12.5px; color: ${p.colors.muted};
          margin: 0 0 8px; line-height: 1.55; max-width: 280px;
        }
        .qq-preview-empty-state-cta { margin-top: 4px; }
      `}</style>
    </div>
  );
}
