// TemplateGallery — Wave H7.
//
// Two surfaces, sharing the same card layout:
//
//  - <TemplateStrip/> — slim, single-row horizontal scroller mounted at the
//    TOP of the Build tab. The first card is "Start blank"; the rest are
//    the TEMPLATE_PRESETS in catalogue order. A "Browse all" button opens
//    the modal below for vertical / categorised browsing.
//
//  - <TemplateBrowseModal/> — vertical browser shown over the editor when
//    the user wants the full list. Categorised by `TemplateConfig.category`,
//    closed via × or backdrop click. No new deps.
//
// Card click applies the template via `onApplyTemplate(template)` —
// WizardShell replaces fields / calculations / layout / header / results
// from `getTemplatePreset(id)`. The blank card calls with `null`.
//
// Mobile: same horizontal scroller. Drag-to-scroll on mouse, native
// touch swipe on phones. The Browse-all modal is full-screen on phones.

import { useEffect, useMemo, useRef, useState, type ReactNode, type MouseEvent as ReactMouseEvent } from 'react';
import { useQuery } from '@tanstack/react-query';
import { X } from 'lucide-react';
import { platformTheme } from '@/theme/platformTheme';
import { dashboardTheme } from '@/theme/dashboardTheme';
import {
  TEMPLATE_PRESETS as STATIC_TEMPLATE_PRESETS, type TemplateConfig,
} from '@shared/templatePresets';
import TemplateMockup from './TemplateMockup';

/**
 * Elfsight-style thumbnail pipeline. Each template ships a pre-rendered PNG
 * generated by `scripts/generate-template-thumbnails.ts` at
 * `/template-thumbnails/<id>@2x.png`. The card renders that PNG first
 * (lazy-loaded). If the PNG is missing (e.g. dev hasn't run the script yet,
 * or a new template hasn't been snapshotted) the `<img>` `onError` flips
 * the id into a "missing" set, and the existing `<TemplateMockup>` from
 * PR #528 renders as the fallback. This is the same approach Elfsight uses
 * in their gallery (the `<uuid>@2x.png` requests in their network panel).
 */
function thumbnailUrl(id: string): string {
  return `/template-thumbnails/${encodeURIComponent(id)}@2x.png`;
}

interface ThumbnailProps {
  template: TemplateConfig;
  /** Shared "ids that failed to load" set so cards survive list re-renders. */
  missing: Set<string>;
  onMissing: (id: string) => void;
}

/**
 * PNG-first thumbnail. Renders an `<img>` pointing at the static thumbnail
 * and falls back to the existing `<TemplateMockup>` when the PNG isn't
 * available. The wrapper preserves the `.qq-tg-mockup` sizing so card
 * layout doesn't shift between PNG / fallback.
 */
function TemplateThumbnail({ template, missing, onMissing }: ThumbnailProps) {
  if (missing.has(template.id)) {
    return <TemplateMockup template={template} />;
  }
  return (
    <img
      src={thumbnailUrl(template.id)}
      loading="lazy"
      decoding="async"
      alt={template.name}
      draggable={false}
      style={{
        width: '100%',
        height: '100%',
        objectFit: 'cover',
        borderRadius: 'inherit',
        display: 'block',
        userSelect: 'none',
      }}
      onError={() => onMissing(template.id)}
    />
  );
}

/**
 * Wave W-AI-2 — admin-editable template catalogue.
 *
 * The wizard fetches the merged (code default + admin override) template
 * list from `/api/quotequick/templates` via TanStack Query. While the
 * fetch is in flight (or on SSR / initial paint) we fall back to the
 * static `TEMPLATE_PRESETS` import so the gallery is never blank.
 */
function useMergedTemplates(): TemplateConfig[] {
  const { data } = useQuery<{ templates: TemplateConfig[] }>({
    queryKey: ['quotequick', 'templates'],
    queryFn: async () => {
      const r = await fetch('/api/quotequick/templates');
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      return r.json();
    },
    // Spec allows up to 60s staleness — cached endpoint matches.
    staleTime: 60_000,
    gcTime: 5 * 60_000,
    refetchOnWindowFocus: false,
  });
  return data?.templates ?? STATIC_TEMPLATE_PRESETS;
}

/** Derive the unique categories from the merged template list (sorted). */
function deriveCategories(templates: TemplateConfig[]): string[] {
  const set = new Set<string>();
  for (const t of templates) if (t.category) set.add(t.category);
  return Array.from(set).sort();
}

/* P1 RE-FIX — `formatTradeId` (snake_case → Title Case) was used to
 * render the strip card's third title line ("Auto Detailing" under
 * "Car Towing"). That third title is now removed entirely (one title
 * per card), so the helper was deleted along with the JSX that
 * called it. */

const p = platformTheme;
const d = dashboardTheme;

/** What WizardShell needs to know to apply a template — null = start blank. */
export type ApplyTemplatePayload = TemplateConfig | null;

/* ───────────────────────────────────────────────────────────── */
/* TemplateCardHover — wraps each card button, mounts a floating  */
/* description tooltip on 350ms+ hover (desktop) or a slide-up    */
/* bottom sheet on touch tap (mobile).                            */
/* ───────────────────────────────────────────────────────────── */

const HOVER_DELAY_MS = 350;

/** Format a snake/kebab-case trade slug into a Title-Case label. */
function formatTradeChip(slug: string): string {
  return slug
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

/** Detect a coarse pointer (phones / tablets) — drives tap-vs-hover. */
function useCoarsePointer(): boolean {
  const [coarse, setCoarse] = useState<boolean>(() => {
    if (typeof window === 'undefined' || !window.matchMedia) return false;
    return window.matchMedia('(pointer: coarse)').matches;
  });
  useEffect(() => {
    if (typeof window === 'undefined' || !window.matchMedia) return;
    const mq = window.matchMedia('(pointer: coarse)');
    const onChange = (e: MediaQueryListEvent) => setCoarse(e.matches);
    mq.addEventListener?.('change', onChange);
    return () => mq.removeEventListener?.('change', onChange);
  }, []);
  return coarse;
}

interface TemplateCardHoverProps {
  template: TemplateConfig;
  className: string;
  testId: string;
  onClick: () => void;
  /** Optional aria role override (e.g. `'listitem'` for the strip). */
  role?: string;
  children: ReactNode;
}

function TemplateCardHover({
  template,
  className,
  testId,
  onClick,
  role,
  children,
}: TemplateCardHoverProps) {
  const isCoarse = useCoarsePointer();
  const wrapperRef = useRef<HTMLDivElement | null>(null);
  const buttonRef = useRef<HTMLButtonElement | null>(null);
  const hoverTimer = useRef<number | null>(null);
  const [open, setOpen] = useState(false);
  // `position` describes where to anchor the floating tooltip relative to
  // the card. Mobile uses 'sheet' (slide-up bottom sheet); desktop uses
  // right/left/above depending on viewport room.
  const [position, setPosition] = useState<'right' | 'left' | 'above' | 'sheet'>('right');

  const description = template.description?.trim() || '';
  const chips = template.matchingTrades ?? [];

  const clearTimer = () => {
    if (hoverTimer.current != null) {
      window.clearTimeout(hoverTimer.current);
      hoverTimer.current = null;
    }
  };

  const computePosition = (): 'right' | 'left' | 'above' | 'sheet' => {
    if (isCoarse) return 'sheet';
    const el = buttonRef.current;
    if (!el) return 'right';
    const rect = el.getBoundingClientRect();
    const vw = window.innerWidth;
    const vh = window.innerHeight;
    const TOOLTIP_W = 280;
    const PAD = 12;
    // Prefer right of the card.
    if (rect.right + PAD + TOOLTIP_W <= vw) return 'right';
    if (rect.left - PAD - TOOLTIP_W >= 0) return 'left';
    if (rect.top >= 200) return 'above';
    return 'right';
  };

  const openTooltip = () => {
    setPosition(computePosition());
    setOpen(true);
  };

  // Hover handlers (desktop / fine pointer). Touch devices skip these and
  // toggle via the click handler below.
  const onPointerEnter = () => {
    if (isCoarse) return;
    clearTimer();
    hoverTimer.current = window.setTimeout(openTooltip, HOVER_DELAY_MS);
  };
  const onPointerLeave = () => {
    if (isCoarse) return;
    clearTimer();
    setOpen(false);
  };
  const onFocus = () => {
    if (isCoarse) return;
    clearTimer();
    hoverTimer.current = window.setTimeout(openTooltip, HOVER_DELAY_MS);
  };
  const onBlur = () => {
    if (isCoarse) return;
    clearTimer();
    setOpen(false);
  };

  // Touch tap: first tap opens the bottom sheet; second tap applies.
  // On fine pointers, click always applies (tooltip is purely informational).
  const handleClick = (e: ReactMouseEvent<HTMLButtonElement>) => {
    if (isCoarse && !open && (description || chips.length > 0)) {
      e.preventDefault();
      e.stopPropagation();
      openTooltip();
      return;
    }
    onClick();
  };

  // Escape closes; click outside (sheet) closes via backdrop handler.
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setOpen(false);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [open]);

  useEffect(() => () => clearTimer(), []);

  const hasTooltipContent = description.length > 0 || chips.length > 0;

  return (
    <div
      ref={wrapperRef}
      className="qq-tg-card-hover-wrap"
      onMouseEnter={onPointerEnter}
      onMouseLeave={onPointerLeave}
    >
      <button
        ref={buttonRef}
        type="button"
        className={className}
        data-testid={testId}
        onClick={handleClick}
        onFocus={onFocus}
        onBlur={onBlur}
        role={role}
        aria-describedby={open ? `tpl-hover-${template.id}` : undefined}
      >
        {children}
      </button>
      {open && hasTooltipContent && position !== 'sheet' && (
        <div
          id={`tpl-hover-${template.id}`}
          className={`qq-tg-hover-pop qq-tg-hover-pop--${position}`}
          role="tooltip"
          data-testid={`template-hover-${template.id}`}
        >
          <h4 className="qq-tg-hover-title">{template.name}</h4>
          {description && (
            <p className="qq-tg-hover-desc">{description}</p>
          )}
          {chips.length > 0 && (
            <div className="qq-tg-hover-best">
              <span className="qq-tg-hover-best-label">Best for:</span>
              <div className="qq-tg-hover-chips">
                {chips.map((c) => (
                  <span key={c} className="qq-tg-hover-chip">{formatTradeChip(c)}</span>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
      {open && hasTooltipContent && position === 'sheet' && (
        <div
          className="qq-tg-hover-sheet-backdrop"
          onClick={(e) => { e.stopPropagation(); setOpen(false); }}
          data-testid={`template-hover-sheet-${template.id}`}
        >
          <div
            className="qq-tg-hover-sheet"
            onClick={(e) => e.stopPropagation()}
            role="dialog"
            aria-label={`${template.name} details`}
          >
            <div className="qq-tg-hover-sheet-handle" aria-hidden="true" />
            <h4 className="qq-tg-hover-title">{template.name}</h4>
            {description && (
              <p className="qq-tg-hover-desc">{description}</p>
            )}
            {chips.length > 0 && (
              <div className="qq-tg-hover-best">
                <span className="qq-tg-hover-best-label">Best for:</span>
                <div className="qq-tg-hover-chips">
                  {chips.map((c) => (
                    <span key={c} className="qq-tg-hover-chip">{formatTradeChip(c)}</span>
                  ))}
                </div>
              </div>
            )}
            <button
              type="button"
              className="qq-tg-hover-sheet-apply"
              onClick={() => { setOpen(false); onClick(); }}
            >
              Use this template
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

/* ───────────────────────────────────────────────────────────── */
/* TemplateStrip — horizontal scrolling row at the top of Build. */
/* ───────────────────────────────────────────────────────────── */

interface StripProps {
  /** When non-null, the card with this id gets the "is-active" ring. */
  activeTemplateId?: string;
  /** Called with the picked template, or null for "Start blank". */
  onApplyTemplate: (next: ApplyTemplatePayload) => void;
}

export default function TemplateStrip({ activeTemplateId, onApplyTemplate }: StripProps) {
  const [open, setOpen] = useState(false);
  const scrollerRef = useRef<HTMLDivElement | null>(null);
  const templates = useMergedTemplates();
  // Track template ids whose PNG thumbnail failed to load so we can fall
  // back to the `<TemplateMockup>` render. Persisted across re-renders.
  const [pngMissing, setPngMissing] = useState<Set<string>>(() => new Set());
  const markMissing = (id: string) =>
    setPngMissing((prev) => {
      if (prev.has(id)) return prev;
      const next = new Set(prev);
      next.add(id);
      return next;
    });

  // Mouse-drag-to-scroll. Touch-swipe is native to overflow-x: auto on
  // mobile so we only special-case desktop pointer drag.
  useEffect(() => {
    const el = scrollerRef.current;
    if (!el) return;
    let isDown = false;
    let startX = 0;
    let scrollLeft = 0;
    const onDown = (e: MouseEvent) => {
      isDown = true;
      el.classList.add('is-dragging');
      startX = e.pageX - el.offsetLeft;
      scrollLeft = el.scrollLeft;
    };
    const onLeave = () => { isDown = false; el.classList.remove('is-dragging'); };
    const onUp = () => { isDown = false; el.classList.remove('is-dragging'); };
    const onMove = (e: MouseEvent) => {
      if (!isDown) return;
      e.preventDefault();
      const x = e.pageX - el.offsetLeft;
      const walk = (x - startX) * 1.2;
      el.scrollLeft = scrollLeft - walk;
    };
    el.addEventListener('mousedown', onDown);
    el.addEventListener('mouseleave', onLeave);
    el.addEventListener('mouseup', onUp);
    el.addEventListener('mousemove', onMove);
    return () => {
      el.removeEventListener('mousedown', onDown);
      el.removeEventListener('mouseleave', onLeave);
      el.removeEventListener('mouseup', onUp);
      el.removeEventListener('mousemove', onMove);
    };
  }, []);

  return (
    <section
      className="qq-tg-strip-section"
      data-testid="template-strip-section"
      aria-label="Start from a template"
    >
      <div className="qq-tg-strip-header">
        <div>
          <h3 className="qq-tg-strip-h">Start from a template</h3>
          {/* Wave L T1 — subtitle removed. The section title alone is enough;
           * the strip below already shows the templates and a card count
           * isn't critical context. */}
        </div>
        <button
          type="button"
          className="qq-tg-browse-all"
          onClick={() => setOpen(true)}
          data-testid="template-browse-all"
        >
          Browse all
        </button>
      </div>

      <div
        ref={scrollerRef}
        className="qq-tg-strip"
        data-testid="template-strip-scroller"
        role="list"
        tabIndex={0}
      >
        {/* "Start blank" card — always first. */}
        <button
          type="button"
          className={`qq-tg-card qq-tg-card-blank${!activeTemplateId ? ' is-active' : ''}`}
          data-testid="template-card-blank"
          onClick={() => onApplyTemplate(null)}
          role="listitem"
        >
          <div className="qq-tg-mockup qq-tg-mockup-blank" aria-hidden="true">
            <span className="qq-tg-plus">+</span>
          </div>
          <div className="qq-tg-card-body">
            <span className="qq-tg-card-name">Start blank</span>
          </div>
        </button>

        {templates.map((t) => {
          const isActive = t.id === activeTemplateId;
          // P1 RE-FIX — the strip card's third title line (formerly
          // `formatTradeId(t.trades[0..2])`, e.g. "Auto Detailing" under
          // "Car Towing") is dropped entirely. Each card now shows ONE
          // title (the template name) on top of the mockup. The mockup's
          // CTA button text is the template's own content and stays.
          return (
            <TemplateCardHover
              key={t.id}
              template={t}
              className={`qq-tg-card${isActive ? ' is-active' : ''}`}
              testId={`template-strip-card-${t.id}`}
              onClick={() => onApplyTemplate(t)}
              role="listitem"
            >
              <div className="qq-tg-mockup">
                <TemplateThumbnail template={t} missing={pngMissing} onMissing={markMissing} />
              </div>
              <div className="qq-tg-card-body">
                <span className="qq-tg-card-name">{t.name}</span>
              </div>
            </TemplateCardHover>
          );
        })}
      </div>

      {open && (
        <TemplateBrowseModal
          onClose={() => setOpen(false)}
          onApplyTemplate={(payload) => {
            onApplyTemplate(payload);
            setOpen(false);
          }}
          activeTemplateId={activeTemplateId}
        />
      )}

      <style>{`
        .qq-tg-strip-section { display: flex; flex-direction: column; gap: 10px; }
        .qq-tg-strip-header {
          display: flex; align-items: flex-end; justify-content: space-between;
          gap: 12px;
        }
        .qq-tg-strip-h {
          font-size: 13px; font-weight: 700; color: ${p.colors.heading};
          margin: 0 0 2px; letter-spacing: -0.005em;
        }
        .qq-tg-strip-sub {
          font-size: 11.5px; color: ${p.colors.muted}; margin: 0;
        }
        /* Wave L T2 — smaller "Browse all" — closer to secondary-link weight
         * than a card-CTA button. Reduced font, padding, and min-height. */
        .qq-tg-browse-all {
          font: inherit; font-size: 11.5px; font-weight: 600;
          color: ${p.colors.accent}; background: transparent;
          border: 1px solid ${p.colors.border}; border-radius: 6px;
          padding: 4px 9px; cursor: pointer;
          min-height: 26px; white-space: nowrap;
          transition: background 0.12s ease, border-color 0.12s ease;
        }
        .qq-tg-browse-all:hover {
          background: ${p.colors.surfaceRaised};
          border-color: ${p.colors.accent};
        }

        /* The strip: single row, horizontal scroll. */
        .qq-tg-strip {
          display: flex; flex-direction: row; flex-wrap: nowrap;
          gap: 10px;
          overflow-x: auto;
          overflow-y: hidden;
          padding: 4px 2px 12px;
          scroll-snap-type: x proximity;
          scroll-behavior: smooth;
          -webkit-overflow-scrolling: touch;
          scrollbar-width: thin;
        }
        .qq-tg-strip.is-dragging { cursor: grabbing; user-select: none; }
        .qq-tg-strip::-webkit-scrollbar { height: 6px; }
        .qq-tg-strip::-webkit-scrollbar-thumb {
          background: ${p.colors.border}; border-radius: 3px;
        }

        /* P2 — card sized to 4:5 aspect (180×225 desktop). Mockup flex-fills
         * the top ~80%; title sits at the BOTTOM, centered, 1-line ellipsis. */
        .qq-tg-card {
          flex: 0 0 auto;
          width: 180px;
          aspect-ratio: 4 / 5;
          background: #fff;
          border: 1px solid ${p.colors.border};
          border-radius: 10px;
          padding: 8px;
          display: flex; flex-direction: column; gap: 4px;
          cursor: pointer;
          scroll-snap-align: start;
          text-align: center;
          font: inherit;
          box-sizing: border-box;
          transition: border-color 0.12s ease, box-shadow 0.12s ease, transform 0.06s ease;
        }
        .qq-tg-card:hover {
          border-color: ${p.colors.accent};
          box-shadow: ${p.shadows.button};
        }
        .qq-tg-card.is-active {
          border-color: ${p.colors.accent};
          box-shadow: 0 0 0 2px ${p.colors.accentLighter};
        }
        /* P2 — body sits at card bottom, centered horizontally.
         * Fixed-ish height keeps title row aligned across cards. */
        .qq-tg-card-body {
          display: flex; flex-direction: column;
          align-items: center;
          justify-content: center;
          padding: 0 2px 2px;
          flex-shrink: 0;
        }
        .qq-tg-card-name {
          font-size: 12px; font-weight: 700; color: ${p.colors.heading};
          line-height: 1.25;
          text-align: center;
          width: 100%;
          overflow: hidden; text-overflow: ellipsis;
          display: -webkit-box; -webkit-line-clamp: 1; -webkit-box-orient: vertical;
          white-space: nowrap;
        }

        /* Mini-mockup. P2 — mockup now flex-fills the card top (~80%) so the
         * outer card can drive the aspect ratio. Was a fixed 150px height. */
        .qq-tg-mockup {
          width: 100%;
          flex: 1 1 auto;
          min-height: 0;
          background: ${d.colors.canvas};
          border-radius: 8px;
          padding: 0;
          box-sizing: border-box;
          display: flex; flex-direction: column; gap: 4px;
          overflow: hidden;
          position: relative;
        }
        .qq-tg-mockup-blank {
          display: flex; align-items: center; justify-content: center;
        }
        .qq-tg-plus {
          font-size: 28px; font-weight: 300; color: ${p.colors.muted};
          line-height: 1;
        }

        /* Mobile — slightly smaller cards. Wave L T2: the smaller browse-all
         * still meets the 32px tap-target threshold (Apple HIG; not 44 in
         * this context because it's a tertiary navigation control, not a
         * primary action). */
        @media (max-width: 768px) {
          /* P2 — mobile cards keep the 4:5 ratio (160 × 200). Card itself
           * remains a 44px+ tap target; aspect-ratio keeps the height. */
          .qq-tg-card { width: 160px; }
          .qq-tg-browse-all { min-height: 32px; padding: 4px 10px; font-size: 12px; }
        }

        /* Template design v2 (Phase 1) — hover wrapper + floating tooltip
         * + mobile bottom sheet. Global selectors so the same CSS applies
         * inside both the strip and the modal grid. */
        .qq-tg-card-hover-wrap {
          position: relative;
          display: inline-flex;
        }
        .qq-tg-modal-grid .qq-tg-card-hover-wrap {
          display: flex; width: 100%;
        }
        .qq-tg-modal-grid .qq-tg-card-hover-wrap .qq-tg-card {
          width: 100%;
        }
        .qq-tg-hover-pop {
          position: absolute;
          z-index: 1300;
          width: 280px; max-width: 280px;
          background: #fff;
          border: 1px solid ${p.colors.borderLight};
          border-radius: 12px;
          box-shadow: ${p.shadows.xl};
          padding: 14px 14px 12px;
          display: flex; flex-direction: column; gap: 8px;
          pointer-events: none;
          animation: qq-tg-hover-fade-in 140ms ease-out;
        }
        @media (prefers-reduced-motion: reduce) {
          .qq-tg-hover-pop { animation: none; }
        }
        @keyframes qq-tg-hover-fade-in {
          from { opacity: 0; transform: translateY(2px); }
          to   { opacity: 1; transform: translateY(0); }
        }
        .qq-tg-hover-pop--right {
          left: calc(100% + 10px); top: 0;
        }
        .qq-tg-hover-pop--left {
          right: calc(100% + 10px); top: 0;
        }
        .qq-tg-hover-pop--above {
          bottom: calc(100% + 10px); left: 0;
        }
        .qq-tg-hover-title {
          margin: 0;
          font-size: 14px; font-weight: 800;
          color: ${p.colors.heading};
          line-height: 1.25;
        }
        .qq-tg-hover-desc {
          margin: 0;
          font-size: 12.5px; font-weight: 400;
          color: ${p.colors.muted};
          line-height: 1.45;
        }
        .qq-tg-hover-best {
          display: flex; flex-direction: column; gap: 6px;
          padding-top: 6px;
          border-top: 1px solid ${p.colors.borderLight};
        }
        .qq-tg-hover-best-label {
          font-size: 11px; font-weight: 700;
          color: ${p.colors.heading};
          text-transform: uppercase;
          letter-spacing: 0.04em;
        }
        .qq-tg-hover-chips {
          display: flex; flex-wrap: wrap; gap: 5px;
        }
        .qq-tg-hover-chip {
          font-size: 11px; font-weight: 600;
          color: ${p.colors.accent};
          background: ${p.colors.accentLighter};
          border-radius: 999px;
          padding: 3px 9px;
          white-space: nowrap;
          line-height: 1.4;
        }

        /* Mobile / touch — slide-up bottom sheet replaces the floating pop. */
        .qq-tg-hover-sheet-backdrop {
          position: fixed; inset: 0; z-index: 1300;
          background: rgba(15, 23, 42, 0.45);
          display: flex; align-items: flex-end; justify-content: center;
          animation: qq-tg-sheet-backdrop-in 160ms ease-out;
        }
        .qq-tg-hover-sheet {
          width: 100%;
          background: #fff;
          border-top-left-radius: 16px; border-top-right-radius: 16px;
          padding: 12px 16px 20px;
          display: flex; flex-direction: column; gap: 10px;
          box-shadow: 0 -8px 28px rgba(15, 23, 42, 0.2);
          animation: qq-tg-sheet-slide-up 220ms cubic-bezier(0.2, 0.7, 0.2, 1);
        }
        @media (prefers-reduced-motion: reduce) {
          .qq-tg-hover-sheet-backdrop,
          .qq-tg-hover-sheet { animation: none; }
        }
        @keyframes qq-tg-sheet-backdrop-in {
          from { opacity: 0; } to { opacity: 1; }
        }
        @keyframes qq-tg-sheet-slide-up {
          from { transform: translateY(100%); }
          to   { transform: translateY(0); }
        }
        .qq-tg-hover-sheet-handle {
          width: 36px; height: 4px; border-radius: 2px;
          background: ${p.colors.border};
          margin: 2px auto 6px;
        }
        .qq-tg-hover-sheet-apply {
          margin-top: 6px;
          font: inherit; font-size: 14px; font-weight: 700;
          color: #fff;
          background: ${p.colors.accent};
          border: none; border-radius: 10px;
          padding: 12px 14px; min-height: 44px;
          cursor: pointer;
        }
        .qq-tg-hover-sheet-apply:hover {
          filter: brightness(0.95);
        }
      `}</style>
    </section>
  );
}

/* ───────────────────────────────────────────────────────────── */
/* TemplateBrowseModal — full-list categorised browser.          */
/* ───────────────────────────────────────────────────────────── */

interface ModalProps {
  activeTemplateId?: string;
  onClose: () => void;
  onApplyTemplate: (next: ApplyTemplatePayload) => void;
}

function TemplateBrowseModal({ activeTemplateId, onClose, onApplyTemplate }: ModalProps) {
  const templates = useMergedTemplates();
  const categories = useMemo(() => deriveCategories(templates), [templates]);
  const [activeCategory, setActiveCategory] = useState<string>('All');
  // Wave M — search field (case-insensitive substring on name). Combines
  // with the active category (AND logic).
  const [search, setSearch] = useState<string>('');
  // Modal-local "PNG failed to load" set — matches the strip's behaviour.
  const [pngMissing, setPngMissing] = useState<Set<string>>(() => new Set());
  const markMissing = (id: string) =>
    setPngMissing((prev) => {
      if (prev.has(id)) return prev;
      const next = new Set(prev);
      next.add(id);
      return next;
    });

  const visible = useMemo(() => {
    const q = search.trim().toLowerCase();
    const byCat = activeCategory === 'All'
      ? templates
      : templates.filter((t) => t.category === activeCategory);
    if (!q) return byCat;
    return byCat.filter((t) => t.name.toLowerCase().includes(q));
  }, [activeCategory, search, templates]);

  // ESC to close.
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [onClose]);

  return (
    <div
      className="qq-tg-modal-backdrop"
      role="dialog"
      aria-modal="true"
      aria-label="Browse all templates"
      data-testid="template-browse-modal"
      onClick={onClose}
    >
      <div
        className="qq-tg-modal"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="qq-tg-modal-header">
          <h2 className="qq-tg-modal-title">Browse all templates</h2>
          <button
            type="button"
            className="qq-tg-modal-close"
            onClick={onClose}
            aria-label="Close template browser"
            data-testid="template-browse-close"
          >
            <X size={18} aria-hidden="true" />
          </button>
        </div>
        {/* Wave M — search field. Filters by template name (case-insensitive
            substring) and combines with the active category. */}
        <div className="qq-tg-modal-search">
          <input
            type="search"
            className="qq-tg-modal-search-input"
            placeholder="Search templates..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            aria-label="Search templates"
            data-testid="template-browse-search"
          />
        </div>
        {/* Wave Q-Hotfix — category filter is now a dropdown <select>
            (per user request). The previous Wave M chips strip was
            scroll-x with a fade mask; the dropdown is more compact and
            doesn't require horizontal swiping to discover categories. */}
        <div className="qq-tg-modal-filter-row">
          <select
            id="qq-tg-modal-cat-select"
            className="qq-tg-modal-cat-select"
            value={activeCategory}
            onChange={(e) => setActiveCategory(e.target.value)}
            data-testid="template-browse-cat-select"
            aria-label="Filter templates by category"
          >
            <option value="All">All categories ({templates.length})</option>
            {categories.map((c) => {
              const count = templates.filter((t) => t.category === c).length;
              return (
                <option key={c} value={c}>
                  {c} ({count})
                </option>
              );
            })}
          </select>
        </div>
        <div className="qq-tg-modal-grid" data-testid="template-browse-grid">
          {visible.map((t) => {
            const isActive = t.id === activeTemplateId;
            // Template design v2 (Phase 1) — subtitle removed from the card
            // itself; the description now lives in the hover modal (see
            // `<TemplateCardHover/>` below) along with a "Best for:" chip row.
            return (
              <TemplateCardHover
                key={t.id}
                template={t}
                className={`qq-tg-card qq-tg-card--with-desc${isActive ? ' is-active' : ''}`}
                testId={`template-browse-card-${t.id}`}
                onClick={() => onApplyTemplate(t)}
              >
                <div className="qq-tg-mockup">
                  <TemplateThumbnail template={t} missing={pngMissing} onMissing={markMissing} />
                </div>
                <div className="qq-tg-card-body">
                  <span className="qq-tg-card-name">{t.name}</span>
                </div>
              </TemplateCardHover>
            );
          })}
          {visible.length === 0 && (
            <p className="qq-tg-modal-empty" data-testid="template-browse-empty">
              No templates match "{search}".
            </p>
          )}
        </div>
      </div>

      <style>{`
        .qq-tg-modal-backdrop {
          position: fixed; inset: 0; z-index: 1200;
          background: rgba(15, 23, 42, 0.55);
          backdrop-filter: blur(2px);
          -webkit-backdrop-filter: blur(2px);
          display: flex; align-items: center; justify-content: center;
          padding: 24px;
        }
        .qq-tg-modal {
          background: #fff; border-radius: 14px;
          /* Wave R-pre v2 — tightened from 880 to 720 max-width and added
           * 78vh max-height on desktop so the modal doesn't dominate the
           * screen. The audit pass found the old 880×86vh was felt as
           * "huge" relative to the actual content shown. */
          width: 100%; max-width: 720px;
          max-height: 78vh; display: flex; flex-direction: column;
          box-shadow: ${p.shadows.xl};
          overflow: hidden;
        }
        .qq-tg-modal-header {
          display: flex; align-items: center; justify-content: space-between;
          padding: 14px 18px;
          border-bottom: 1px solid ${p.colors.borderLight};
        }
        .qq-tg-modal-title {
          margin: 0; font-size: 14px; font-weight: 800; color: ${p.colors.heading};
        }
        /* Wave R-pre v2 — close button restyled. Was 32×32 round, muted
         * grey, hard to spot. Now 40×40, heading-coloured X icon, with a
         * subtle background ring + a clear surfaceRaised hover. */
        .qq-tg-modal-close {
          width: 40px; height: 40px; border-radius: 50%;
          background: ${p.colors.surfaceRaised};
          border: 1px solid ${p.colors.border};
          color: ${p.colors.heading};
          cursor: pointer;
          display: flex; align-items: center; justify-content: center;
          flex-shrink: 0;
          transition: background 0.12s ease, border-color 0.12s ease, color 0.12s ease;
        }
        .qq-tg-modal-close:hover {
          background: ${p.colors.danger ?? '#dc2626'};
          border-color: ${p.colors.danger ?? '#dc2626'};
          color: #fff;
        }
        .qq-tg-modal-close:focus-visible {
          outline: none;
          box-shadow: 0 0 0 3px ${p.colors.accentLighter};
        }
        /* Wave M — search bar above the category chips. */
        .qq-tg-modal-search {
          padding: 12px 18px 4px;
          flex-shrink: 0;
        }
        .qq-tg-modal-search-input {
          width: 100%; box-sizing: border-box;
          font: inherit; font-size: 13px;
          padding: 9px 12px;
          border: 1px solid ${p.colors.border};
          border-radius: 9px;
          background: #fff; color: ${p.colors.heading};
          transition: border-color 0.12s ease, box-shadow 0.12s ease;
        }
        .qq-tg-modal-search-input::placeholder {
          color: ${p.colors.muted};
        }
        .qq-tg-modal-search-input:focus {
          outline: none;
          border-color: ${p.colors.accent};
          box-shadow: 0 0 0 3px ${p.colors.accentLighter};
        }
        /* Wave Q-Hotfix — dropdown filter (replaces Wave M chips). */
        .qq-tg-modal-filter-row {
          display: flex; align-items: center; gap: 10px;
          padding: 10px 18px;
          border-bottom: 1px solid ${p.colors.borderLight};
          flex-shrink: 0;
        }
        .qq-tg-modal-cat-select {
          flex: 1; min-width: 0;
          font: inherit; font-size: 13px; font-weight: 600;
          color: ${p.colors.heading};
          background: #fff;
          border: 1px solid ${p.colors.border};
          border-radius: 8px;
          padding: 8px 12px; min-height: 38px;
          cursor: pointer;
          outline: none;
        }
        .qq-tg-modal-cat-select:focus {
          border-color: ${p.colors.accent};
        }
        .qq-tg-modal-grid {
          padding: 16px 18px 24px;
          display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px;
          grid-auto-rows: 1fr;
          overflow-y: auto;
        }
        /* Wave R-pre W-CARDS — force equal card heights per row.
         * grid-auto-rows: 1fr above makes every row in the modal grid
         * stretch to the tallest cell. W-AP-1 bumped from 178 → 250 to
         * make room for the new 150px mockup (vs 76px before) plus the
         * 2-line description + name. */
        .qq-tg-modal-grid .qq-tg-card,
        .qq-tg-modal-grid .qq-tg-card--with-desc {
          height: 100%;
          min-height: 250px;
        }
        /* W-AO-2 — modal card body now hosts BOTH the name (centered,
         * bold) and a 2-line clamped description below (11px, muted).
         * Switched from center-aligned name to top-aligned stack so
         * 1-line and 2-line titles still share a row baseline via the
         * fixed body min-height. */
        .qq-tg-card--with-desc .qq-tg-card-body {
          min-height: 64px;
          padding: 6px 6px 8px;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: flex-start;
          gap: 2px;
          flex: 1 1 auto;
        }
        .qq-tg-card--with-desc .qq-tg-card-name {
          font-size: 13px;
          font-weight: 700;
          color: ${p.colors.heading};
          line-height: 1.3;
          -webkit-line-clamp: 1;
          white-space: normal;
          text-align: center;
          width: 100%;
        }
        .qq-tg-card-desc {
          font-size: 11px;
          font-weight: 500;
          color: ${p.colors.muted};
          line-height: 1.35;
          text-align: center;
          width: 100%;
          overflow: hidden;
          text-overflow: ellipsis;
          display: -webkit-box;
          -webkit-line-clamp: 2;
          -webkit-box-orient: vertical;
        }
        .qq-tg-modal-empty {
          grid-column: 1 / -1;
          text-align: center;
          font-size: 12.5px; color: ${p.colors.muted};
          padding: 28px 8px;
          margin: 0;
        }
        @media (max-width: 768px) {
          .qq-tg-modal-backdrop { padding: 8px; }
          .qq-tg-modal { max-height: 96vh; }
          .qq-tg-modal-grid { grid-template-columns: repeat(2, 1fr); }
          .qq-tg-modal-close { min-width: 44px; min-height: 44px; }
          .qq-tg-modal-search { padding: 10px 12px 4px; }
          .qq-tg-modal-search-input { padding: 11px 12px; min-height: 44px; }
          .qq-tg-modal-filter-row { padding: 10px 12px; }
          .qq-tg-modal-cat-select { min-height: 44px; font-size: 14px; }
        }
      `}</style>
    </div>
  );
}
