/**
 * ContentFlow — Public API. Wave 20.
 *
 * The single content-generation entry point. RankFlow + SocialSync (and any
 * future delivery channel) call `requestContent()` here instead of running
 * their own LLM calls. This file is intentionally thin: it persists the
 * request, fires the existing ContentFlow pipeline (article body / social
 * post / image / video), and writes a pipeline-log row at every stage so
 * the admin dashboard + customer portal surfaces can see what's happening.
 *
 * Architectural decision (Alex, 2026-05-26):
 *   "ContentFlow becomes the only generator. RankFlow handles website
 *    delivery (CMS integration, scheduling, SEO tracking) — calls
 *    ContentFlow for content. SocialSync handles social delivery — calls
 *    ContentFlow for content. Two AI systems coordinating in the backend;
 *    neither I nor users see the boundary. Errors at every stage must
 *    surface in user portal AND admin dashboard."
 *
 * This API does NOT introduce a new pipeline. It dispatches to the
 * existing ContentFlow services:
 *   - articles → articleService.ts (createDraftFromRankflowTask +
 *     generateArticleBody, 3-layer quality gate already canonical here)
 *   - social posts → socialSync/contentGenerator.ts (kept; SocialSync's
 *     platform-specific prompt builder + delivery-side guardrail gate
 *     remain — see audit doc for why)
 *   - images → imageGenerationService.ts (existing)
 *   - videos → videoContentService.ts (existing)
 *
 * Hook for Wave 21: `enqueueContentRequest()` is the single point where
 * the SerpAwareGenerator brain will plug in. No caller (RankFlow /
 * SocialSync) needs to change to gain SERP-aware enrichment.
 */

import crypto from "crypto";
import { db } from "../../db";
import {
  contentRequests,
  contentPipelineLog,
  type ContentRequest as ContentRequestRow,
} from "@shared/schema";
import { and, desc, eq, sql } from "drizzle-orm";
import { createLogger } from "../../lib/logger";

const log = createLogger("ContentFlow:API");

/* ─── Public types ───────────────────────────────────────────────────── */

export type ContentRequestType = "article" | "social_post" | "image" | "video";
export type ContentRequestSource =
  | "rankflow"
  | "socialsync"
  | "contentflow"
  | "manual";
export type ContentRequestStage =
  | "requested"
  | "generating"
  | "quality_check"
  | "approved"
  | "failed";

export interface ContentRequest {
  /** UUID. Caller-supplied OR auto-generated by requestContent. */
  requestId?: string;
  source: ContentRequestSource;
  type: ContentRequestType;
  clientId?: number | null;
  topic: string;
  tone?: string;
  imageStyle?: string;
  targetWordCount?: number;
  targetKeyword?: string;
  /** Free-form caller-supplied metadata (platform, taskId, draftId, etc). */
  metadata?: Record<string, unknown>;
}

export interface ContentError {
  stage:
    | "fetch_brief"
    | "llm_generation"
    | "quality_gate"
    | "humanization"
    | "image_gen"
    | "delivery";
  message: string;
  retryable: boolean;
}

export interface ContentResult {
  requestId: string;
  source: ContentRequestSource;
  type: ContentRequestType;
  clientId: number | null;
  topic: string;
  status: ContentRequestStage;
  payload?: {
    article?: string;
    title?: string;
    excerpt?: string;
    imageUrls?: string[];
    videoUrl?: string;
    draftId?: number;
    metadata?: Record<string, unknown>;
  };
  errors?: ContentError[];
  generatedAt?: Date | null;
  qualityScore?: number | null;
}

/* ─── Internals ──────────────────────────────────────────────────────── */

function newRequestId(): string {
  return crypto.randomUUID();
}

function rowToResult(row: ContentRequestRow): ContentResult {
  const payload = (row.result_payload || undefined) as
    | ContentResult["payload"]
    | undefined;
  return {
    requestId: row.request_id,
    source: row.source as ContentRequestSource,
    type: row.type as ContentRequestType,
    clientId: row.client_id ?? null,
    topic: row.topic,
    status: row.current_stage as ContentRequestStage,
    payload,
    qualityScore: row.quality_score ?? null,
    generatedAt:
      row.current_stage === "approved" ? row.updated_at ?? null : null,
  };
}

async function appendLog(opts: {
  requestId: string;
  source: ContentRequestSource;
  stage: string;
  payload?: Record<string, unknown>;
  errors?: ContentError[];
}): Promise<void> {
  try {
    await db.insert(contentPipelineLog).values({
      request_id: opts.requestId,
      source: opts.source,
      stage: opts.stage,
      payload: opts.payload ?? null,
      errors: opts.errors ?? null,
    });
  } catch (err: any) {
    log.error("pipeline-log write failed", {
      requestId: opts.requestId,
      stage: opts.stage,
      error: err?.message,
    });
  }
}

/* ─── Public API ─────────────────────────────────────────────────────── */

/**
 * Submit a content generation request. Returns the requestId immediately.
 * The actual generation is dispatched asynchronously via the existing
 * ContentFlow / SocialSync pipelines; callers poll `getContent(requestId)`
 * until status === "approved" or "failed".
 *
 * This function never throws on a downstream dispatcher error — it always
 * returns a requestId so the caller can read the failure off
 * `getContent()`. Internal exceptions are converted into a pipeline-log
 * entry + failed-stage write.
 */
export async function requestContent(
  req: ContentRequest,
): Promise<{ requestId: string }> {
  const requestId = req.requestId ?? newRequestId();

  // Persist the request row first.
  await db.insert(contentRequests).values({
    request_id: requestId,
    source: req.source,
    type: req.type,
    client_id: req.clientId ?? null,
    topic: req.topic,
    request_payload: {
      tone: req.tone,
      imageStyle: req.imageStyle,
      targetWordCount: req.targetWordCount,
      targetKeyword: req.targetKeyword,
      metadata: req.metadata ?? {},
    },
    current_stage: "requested",
  });

  await appendLog({
    requestId,
    source: req.source,
    stage: "requested",
    payload: {
      type: req.type,
      topic: req.topic,
      clientId: req.clientId ?? null,
    },
  });

  // Hook for Wave 21 SerpAwareGenerator: insert enrichment step here.
  // The dispatcher below sees the (possibly enriched) request payload.
  enqueueContentRequest(requestId).catch((err) =>
    log.error("dispatcher error", { requestId, error: err?.message }),
  );

  return { requestId };
}

/**
 * Read the current state of a content request. Returns undefined when
 * the requestId is unknown.
 */
export async function getContent(
  requestId: string,
): Promise<ContentResult | undefined> {
  const [row] = await db
    .select()
    .from(contentRequests)
    .where(eq(contentRequests.request_id, requestId))
    .limit(1);
  if (!row) return undefined;
  const result = rowToResult(row);
  if (row.current_stage === "failed") {
    const errs = await db
      .select()
      .from(contentPipelineLog)
      .where(
        and(
          eq(contentPipelineLog.request_id, requestId),
          eq(contentPipelineLog.stage, "failed"),
        ),
      )
      .orderBy(desc(contentPipelineLog.recorded_at))
      .limit(1);
    if (errs[0]?.errors) {
      result.errors = errs[0].errors as ContentError[];
    }
  }
  return result;
}

/**
 * List recent in-flight requests. Optional source filter for the admin
 * pipeline page; `currentStage` filter for a "what failed?" view.
 */
export async function listPending(opts: {
  source?: ContentRequestSource;
  clientId?: number;
  currentStage?: ContentRequestStage;
  limit?: number;
} = {}): Promise<ContentResult[]> {
  const limit = Math.min(500, Math.max(1, opts.limit ?? 100));
  const conditions = [] as any[];
  if (opts.source) conditions.push(eq(contentRequests.source, opts.source));
  if (opts.clientId != null) conditions.push(eq(contentRequests.client_id, opts.clientId));
  if (opts.currentStage)
    conditions.push(eq(contentRequests.current_stage, opts.currentStage));

  const q = db.select().from(contentRequests);
  const rows = conditions.length
    ? await q.where(and(...conditions)).orderBy(desc(contentRequests.created_at)).limit(limit)
    : await q.orderBy(desc(contentRequests.created_at)).limit(limit);
  return rows.map(rowToResult);
}

/* ─── Stage transitions (called by dispatchers) ──────────────────────── */

export async function markStage(
  requestId: string,
  stage: ContentRequestStage,
  patch: Partial<{
    payload: Record<string, unknown>;
    errors: ContentError[];
    qualityScore: number | null;
    draftId: number | null;
  }> = {},
): Promise<void> {
  const updates: Record<string, unknown> = {
    current_stage: stage,
    updated_at: new Date(),
  };
  if (patch.payload !== undefined) updates.result_payload = patch.payload;
  if (patch.qualityScore !== undefined) updates.quality_score = patch.qualityScore;
  if (patch.draftId !== undefined) updates.draft_id = patch.draftId;
  if (patch.errors?.length) {
    updates.error_count = sql`${contentRequests.error_count} + ${patch.errors.length}`;
  }
  const [updated] = await db
    .update(contentRequests)
    .set(updates as any)
    .where(eq(contentRequests.request_id, requestId))
    .returning();
  if (!updated) {
    log.warn("markStage on unknown requestId", { requestId, stage });
    return;
  }
  await appendLog({
    requestId,
    source: updated.source as ContentRequestSource,
    stage,
    payload: patch.payload,
    errors: patch.errors,
  });
}

/* ─── Direct-log helper (no dispatch) ───────────────────────────────── */

/**
 * Record an already-completed generation in the pipeline. Used by callers
 * (e.g. the SocialSync orchestrator) that produce content via direct calls
 * for legacy reasons but still want unified observability. The request
 * lands in content_requests at the final stage with the full payload, and
 * a single content_pipeline_log row is written.
 *
 * Prefer requestContent() for new code. recordCompletedRequest() exists so
 * existing orchestration loops (with their own retry / mix-guard logic)
 * don't have to be rewritten in Wave 20.
 */
export async function recordCompletedRequest(input: {
  source: ContentRequestSource;
  type: ContentRequestType;
  clientId?: number | null;
  topic: string;
  metadata?: Record<string, unknown>;
  outcome:
    | { ok: true; payload: ContentResult["payload"]; qualityScore?: number | null; draftId?: number | null }
    | { ok: false; errors: ContentError[] };
}): Promise<{ requestId: string }> {
  const requestId = newRequestId();
  const stage: ContentRequestStage = input.outcome.ok ? "approved" : "failed";
  await db.insert(contentRequests).values({
    request_id: requestId,
    source: input.source,
    type: input.type,
    client_id: input.clientId ?? null,
    topic: input.topic,
    request_payload: { metadata: input.metadata ?? {} },
    result_payload: input.outcome.ok ? (input.outcome.payload as any) : null,
    quality_score: input.outcome.ok ? input.outcome.qualityScore ?? null : null,
    error_count: input.outcome.ok ? 0 : input.outcome.errors.length,
    draft_id: input.outcome.ok ? input.outcome.draftId ?? null : null,
    current_stage: stage,
  });
  await appendLog({
    requestId,
    source: input.source,
    stage,
    payload: input.outcome.ok ? (input.outcome.payload as any) : undefined,
    errors: input.outcome.ok ? undefined : input.outcome.errors,
  });
  return { requestId };
}

/* ─── Dispatcher — runs the existing ContentFlow pipelines ──────────── */

/**
 * Fan out the request to the right ContentFlow service. Lazy imports avoid
 * a circular dependency between this API module and the article / social
 * services that already import contentflow utilities.
 *
 * The actual work is delegated to existing code paths — this dispatcher
 * is the seam that lets the admin dashboard and customer portal see the
 * generation as a unified pipeline.
 */
export async function enqueueContentRequest(requestId: string): Promise<void> {
  const result = await getContent(requestId);
  if (!result) {
    log.warn("dispatcher: requestId not found", { requestId });
    return;
  }

  await markStage(requestId, "generating");

  try {
    if (result.type === "article") {
      const { dispatchArticleRequest } = await import("./apiDispatchArticle");
      await dispatchArticleRequest(requestId);
    } else if (result.type === "social_post") {
      const { dispatchSocialPostRequest } = await import("./apiDispatchSocial");
      await dispatchSocialPostRequest(requestId);
    } else if (result.type === "image") {
      const { dispatchImageRequest } = await import("./apiDispatchImage");
      await dispatchImageRequest(requestId);
    } else if (result.type === "video") {
      const { dispatchVideoRequest } = await import("./apiDispatchVideo");
      await dispatchVideoRequest(requestId);
    } else {
      await markStage(requestId, "failed", {
        errors: [
          {
            stage: "fetch_brief",
            message: `Unknown content type: ${result.type}`,
            retryable: false,
          },
        ],
      });
    }
  } catch (err: any) {
    log.error("dispatcher exception", { requestId, error: err?.message });
    await markStage(requestId, "failed", {
      errors: [
        {
          stage: "llm_generation",
          message: err?.message ?? "Unknown dispatcher error",
          retryable: true,
        },
      ],
    });
  }
}
